import { createContext, useContext, useState, type ReactNode } from 'react';

export type Language = 'fr' | 'en' | 'wo' | 'dyo' | 'man' | 'ff';

const LANG_KEY = 'casamance-tour-language';

const translations: Record<Language, Record<string, string>> = {
  fr: {
    'nav.discover': 'Découvrir',
    'nav.visit': 'Visiter',
    'nav.activities': 'Activités',
    'nav.gastronomy': 'Gastronomie',
    'nav.guides': 'Guides',
    'guides.title': 'Nos Guides Locaux',
    'guides.subtitle': "Partez à l'aventure avec des experts passionnés. Nos guides sont certifiés et connaissent la Casamance comme leur poche.",
    'nav.accommodations': 'Hébergements',
    'accommodations.title': 'Où dormir ?',
    'accommodations.subtitle': "Du campement villageois authentique à l'éco-lodge de luxe, trouvez le nid parfait pour votre séjour en Casamance.",
    'nav.gallery': 'Galerie',
    'nav.agenda': 'Agenda',
    'nav.testimonials': 'Témoignages',
    'nav.contact': 'Contact',
    'nav.explore': 'Explorer',
    'nav.login': 'Connexion',
    'nav.logout': 'Déconnexion',
    'nav.myBookings': 'Mes réservations',
    'nav.admin': 'Admin',
    'hero.title': 'Découvrez la Magie de la Casamance',
    'hero.subtitle': 'Une aventure inoubliable au cœur du Sénégal',
    'hero.cta': 'Explorer maintenant',
    'hero.book': 'Réserver une visite',
    'booking.title': 'Réserver votre expérience',
    'booking.name': 'Nom complet',
    'booking.email': 'Email',
    'booking.date': 'Date souhaitée',
    'booking.type': 'Type de réservation',
    'booking.region': 'Région',
    'booking.message': 'Message',
    'booking.submit': 'Confirmer la réservation',
    'booking.guide': 'Guide',
    'booking.accommodation': 'Hébergement',
    'booking.activity': 'Activité',
    'booking.gastronomy': 'Gastronomie',
    'booking.discovery': 'Découverte',
    'auth.login': 'Connexion',
    'auth.register': 'Inscription',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.name': 'Nom complet',
    'auth.birthDate': 'Date de naissance',
    'auth.birthPlace': 'Lieu de naissance',
    'auth.submit': 'Se connecter',
    'auth.registerSubmit': 'Créer un compte',
    'auth.forgotPassword': 'Mot de passe oublié ?',
    'auth.noAccount': 'Pas de compte ?',
    'auth.hasAccount': 'Déjà un compte ?',
    'activity.book': 'Réserver',
    'activity.duration': 'Durée',
    'activity.price': 'Prix',
    'guide.book': 'Réserver ce guide',
    'guide.languages': 'Langues',
    'guide.specialty': 'Spécialités',
    'accommodation.book': 'Réserver',
    'accommodation.features': 'Équipements',
    'gastronomy.dishes': 'Plats',
    'gastronomy.drinks': 'Boissons',
    'gastronomy.recipe': 'Recette',
    'gastronomy.ingredients': 'Ingrédients',
    'gallery.title': 'Galerie Photos',
    'gallery.subtitle': 'Les plus beaux paysages de Casamance',
    'agenda.title': 'Agenda Culturel',
    'agenda.subtitle': 'Événements et festivals de Casamance',
    'testimonials.title': 'Témoignages',
    'testimonials.subtitle': 'Ce que disent nos visiteurs',
    'testimonials.addReview': 'Laisser un avis',
    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Nous sommes là pour vous aider',
    'contact.send': 'Envoyer le message',
    'admin.title': 'Tableau de bord Admin',
    'admin.bookings': 'Réservations',
    'admin.media': 'Médias',
    'admin.users': 'Utilisateurs',
    'admin.config': 'Configuration',
    'common.loading': 'Chargement...',
    'common.error': 'Une erreur est survenue',
    'common.success': 'Succès !',
    'common.cancel': 'Annuler',
    'common.confirm': 'Confirmer',
    'common.close': 'Fermer',
    'common.save': 'Enregistrer',
    'common.all': 'Tous',
    'common.seeMore': 'En savoir plus',
    'common.book': 'Réserver',
    'common.back': 'Retour',
    'footer.newsletter': 'Newsletter',
    'footer.newsletterText': 'Recevez nos conseils de voyage et actualités.',
    'footer.subscribe': 'S\'inscrire',
    'footer.services': 'Services',
    'footer.community': 'Communauté',
    'footer.rights': 'Tous droits réservés',
    'footer.s.gastronomy': 'Gastronomie',
    'footer.s.guides': 'Guides Locaux',
    'footer.s.accommodations': 'Hébergements',
    'footer.s.activities': 'Activités',
    'footer.c.gallery': 'Galerie Photos',
    'footer.c.testimonials': 'Témoignages',
    'footer.c.reviews': 'Avis Clients',
    'footer.c.contact': 'Contact',
  },
  en: {
    'nav.discover': 'Discover',
    'nav.visit': 'Visit',
    'nav.activities': 'Activities',
    'nav.gastronomy': 'Gastronomy',
    'nav.guides': 'Guides',
    'guides.title': 'Our Local Guides',
    'guides.subtitle': 'Go on an adventure with passionate experts. Our guides are certified and know Casamance like the back of their hand.',
    'nav.accommodations': 'Accommodations',
    'accommodations.title': 'Where to stay?',
    'accommodations.subtitle': 'From authentic village campsites to luxury eco-lodges, find the perfect nest for your stay in Casamance.',
    'nav.gallery': 'Gallery',
    'nav.agenda': 'Agenda',
    'nav.testimonials': 'Testimonials',
    'nav.contact': 'Contact',
    'nav.explore': 'Explore',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    'nav.myBookings': 'My Bookings',
    'nav.admin': 'Admin',
    'hero.title': 'Discover the Magic of Casamance',
    'hero.subtitle': 'An unforgettable adventure in the heart of Senegal',
    'hero.cta': 'Explore now',
    'hero.book': 'Book a visit',
    'booking.title': 'Book your experience',
    'booking.name': 'Full name',
    'booking.email': 'Email',
    'booking.date': 'Desired date',
    'booking.type': 'Booking type',
    'booking.region': 'Region',
    'booking.message': 'Message',
    'booking.submit': 'Confirm booking',
    'booking.guide': 'Guide',
    'booking.accommodation': 'Accommodation',
    'booking.activity': 'Activity',
    'booking.gastronomy': 'Gastronomy',
    'booking.discovery': 'Discovery',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.name': 'Full name',
    'auth.birthDate': 'Date of birth',
    'auth.birthPlace': 'Place of birth',
    'auth.submit': 'Sign in',
    'auth.registerSubmit': 'Create account',
    'auth.forgotPassword': 'Forgot password?',
    'auth.noAccount': 'No account?',
    'auth.hasAccount': 'Already have an account?',
    'activity.book': 'Book',
    'activity.duration': 'Duration',
    'activity.price': 'Price',
    'guide.book': 'Book this guide',
    'guide.languages': 'Languages',
    'guide.specialty': 'Specialties',
    'accommodation.book': 'Book',
    'accommodation.features': 'Features',
    'gastronomy.dishes': 'Dishes',
    'gastronomy.drinks': 'Drinks',
    'gastronomy.recipe': 'Recipe',
    'gastronomy.ingredients': 'Ingredients',
    'gallery.title': 'Photo Gallery',
    'gallery.subtitle': 'The most beautiful landscapes of Casamance',
    'agenda.title': 'Cultural Agenda',
    'agenda.subtitle': 'Events and festivals in Casamance',
    'testimonials.title': 'Testimonials',
    'testimonials.subtitle': 'What our visitors say',
    'testimonials.addReview': 'Leave a review',
    'contact.title': 'Contact Us',
    'contact.subtitle': 'We are here to help you',
    'contact.send': 'Send message',
    'admin.title': 'Admin Dashboard',
    'admin.bookings': 'Bookings',
    'admin.media': 'Media',
    'admin.users': 'Users',
    'admin.config': 'Configuration',
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.success': 'Success!',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.all': 'All',
    'common.seeMore': 'Learn more',
    'common.book': 'Book',
    'common.back': 'Back',
    'footer.newsletter': 'Newsletter',
    'footer.newsletterText': 'Receive our travel tips and news.',
    'footer.subscribe': 'Subscribe',
    'footer.services': 'Services',
    'footer.community': 'Community',
    'footer.rights': 'All rights reserved',
    'footer.s.gastronomy': 'Gastronomy',
    'footer.s.guides': 'Local Guides',
    'footer.s.accommodations': 'Accommodations',
    'footer.s.activities': 'Activities',
    'footer.c.gallery': 'Photo Gallery',
    'footer.c.testimonials': 'Testimonials',
    'footer.c.reviews': 'Reviews',
    'footer.c.contact': 'Contact',
  },
  wo: {
    'nav.discover': 'Xam-xam',
    'nav.visit': 'Dem',
    'nav.activities': 'Liggéey yi',
    'nav.gastronomy': 'Lekk-ñam',
    'nav.guides': 'Dalal yëgël',
    'nav.accommodations': 'Daay',
    'nav.gallery': 'Tënk-seen',
    'nav.agenda': 'Agenda',
    'nav.testimonials': 'Wax-waxaat',
    'nav.contact': 'Toog ak',
    'nav.explore': 'Xëy',
    'nav.login': 'Dugg',
    'nav.logout': 'Génn',
    'nav.myBookings': 'Sa réservations yi',
    'nav.admin': 'Admin',
    'hero.title': 'Xam sa Casamance Bu Rafeteel',
    'hero.subtitle': 'Xëy ci biir Sénégal',
    'hero.cta': 'Xëy léegi',
    'hero.book': 'Réserver',
    'booking.title': 'Réserver sa xëy',
    'booking.name': 'Sa tur',
    'booking.email': 'Email',
    'booking.date': 'Bes',
    'booking.type': 'Réservation bu xam',
    'booking.region': 'Région',
    'booking.message': 'Kàddu',
    'booking.submit': 'Setal',
    'booking.guide': 'Guide',
    'booking.accommodation': 'Daay',
    'booking.activity': 'Liggéey',
    'booking.gastronomy': 'Lekk-ñam',
    'booking.discovery': 'Xam-xam',
    'auth.login': 'Dugg',
    'auth.register': 'Bindël',
    'auth.email': 'Email',
    'auth.password': 'Dëkk-xam',
    'auth.name': 'Sa tur',
    'auth.birthDate': 'Bes julli',
    'auth.birthPlace': 'Dëkk julli',
    'auth.submit': 'Dugg',
    'auth.registerSubmit': 'Samp kont',
    'auth.forgotPassword': 'Lekkat sa dëkk-xam?',
    'auth.noAccount': 'Amul kont?',
    'auth.hasAccount': 'Am na kont?',
    'activity.book': 'Réserver',
    'activity.duration': 'Yoon wi',
    'activity.price': 'Prix',
    'guide.book': 'Réserver guide bi',
    'guide.languages': 'Làkk yi',
    'guide.specialty': 'Xam-xam',
    'accommodation.book': 'Réserver',
    'accommodation.features': 'Jumtukaay',
    'gastronomy.dishes': 'Ceeb-ñam',
    'gastronomy.drinks': 'Ndox-ñam',
    'gastronomy.recipe': 'Tekki',
    'gastronomy.ingredients': 'Xaar',
    'gallery.title': 'Galerie Picc',
    'gallery.subtitle': 'Casamance rafet',
    'agenda.title': 'Agenda Nguuñ',
    'agenda.subtitle': 'Xëtu Casamance',
    'testimonials.title': 'Wax-waxaat',
    'testimonials.subtitle': 'Jën yi wax',
    'testimonials.addReview': 'Bind sa avis',
    'contact.title': 'Xiif ma',
    'contact.subtitle': 'Noo ci',
    'contact.send': 'Yónnë',
    'admin.title': 'Dashboard Admin',
    'admin.bookings': 'Réservations',
    'admin.media': 'Picc yi',
    'admin.users': 'Nit yi',
    'admin.config': 'Config',
    'common.loading': 'Di ñëw...',
    'common.error': 'Jàpp am',
    'common.success': 'Ganaw!',
    'common.cancel': 'Soppiku',
    'common.confirm': 'Setal',
    'common.close': 'Tëj',
    'common.save': 'Dëkk',
    'common.all': 'Yëpp',
    'common.seeMore': 'Xam ci kanam',
    'common.book': 'Réserver',
    'common.back': 'Dellu',
    'footer.newsletter': 'Newsletter',
    'footer.newsletterText': 'Dem ci kanam',
    'footer.subscribe': 'Bindël',
    'footer.services': 'Liggéey yi',
    'footer.community': 'Jaamu',
    'footer.rights': 'Tëjj',
  },
  dyo: {
    'nav.discover': 'Efang',
    'nav.visit': 'Elur',
    'nav.activities': 'Esukon',
    'nav.gastronomy': 'Eñam',
    'nav.guides': 'Efañ',
    'nav.accommodations': 'Edaw',
    'nav.gallery': 'Etat',
    'nav.agenda': 'Agenda',
    'nav.testimonials': 'Ekafir',
    'nav.contact': 'Ekayen',
    'nav.explore': 'Efan',
    'nav.login': 'Ekaj',
    'nav.logout': 'Ekal',
    'nav.myBookings': 'Reservations am',
    'nav.admin': 'Admin',
    'hero.title': 'Elur Casamance',
    'hero.subtitle': 'Enak Sénégal ambon',
    'hero.cta': 'Efan léegi',
    'hero.book': 'Réserver',
    'booking.title': 'Réserver',
    'booking.name': 'Ekaben',
    'booking.email': 'Email',
    'booking.date': 'Efaj',
    'booking.type': 'Ekayon',
    'booking.region': 'Région',
    'booking.message': 'Ekafan',
    'booking.submit': 'Setal',
    'booking.guide': 'Guide',
    'booking.accommodation': 'Edaw',
    'booking.activity': 'Esukon',
    'booking.gastronomy': 'Eñam',
    'booking.discovery': 'Efang',
    'auth.login': 'Ekaj',
    'auth.register': 'Esam',
    'auth.email': 'Email',
    'auth.password': 'Emaken',
    'auth.name': 'Ekaben',
    'auth.birthDate': 'Efaj ejul',
    'auth.birthPlace': 'Ekan ejul',
    'auth.submit': 'Ekaj',
    'auth.registerSubmit': 'Esam kont',
    'auth.forgotPassword': 'Emaken lekkat?',
    'auth.noAccount': 'Amul kont?',
    'auth.hasAccount': 'Am kont?',
    'activity.book': 'Réserver',
    'activity.duration': 'Ekabal',
    'activity.price': 'Prix',
    'guide.book': 'Réserver efañ',
    'guide.languages': 'Elakk',
    'guide.specialty': 'Efang',
    'accommodation.book': 'Réserver',
    'accommodation.features': 'Ekayon',
    'gastronomy.dishes': 'Eñamok',
    'gastronomy.drinks': 'Endowok',
    'gastronomy.recipe': 'Ekaben',
    'gastronomy.ingredients': 'Esukon',
    'gallery.title': 'Galerie',
    'gallery.subtitle': 'Casamance ekafan',
    'agenda.title': 'Agenda',
    'agenda.subtitle': 'Xëtu Casamance',
    'testimonials.title': 'Ekafir',
    'testimonials.subtitle': 'Nit yi wax',
    'testimonials.addReview': 'Ekan avis',
    'contact.title': 'Ekayen',
    'contact.subtitle': 'Noo ci',
    'contact.send': 'Yónnë',
    'admin.title': 'Admin',
    'admin.bookings': 'Réservations',
    'admin.media': 'Etat',
    'admin.users': 'Nit',
    'admin.config': 'Config',
    'common.loading': 'Enand...',
    'common.error': 'Ekaj',
    'common.success': 'Setal!',
    'common.cancel': 'Eka',
    'common.confirm': 'Setal',
    'common.close': 'Tëj',
    'common.save': 'Ekan',
    'common.all': 'Yëpp',
    'common.seeMore': 'Efang',
    'common.book': 'Réserver',
    'common.back': 'Dellu',
    'footer.newsletter': 'Newsletter',
    'footer.newsletterText': 'Dem ci kanam',
    'footer.subscribe': 'Esam',
    'footer.services': 'Esukon',
    'footer.community': 'Jaamu',
    'footer.rights': 'Tëjj',
  },
  man: {
    'nav.discover': 'Hakili',
    'nav.visit': 'Taa',
    'nav.activities': 'Baara',
    'nav.gastronomy': 'Duminiya',
    'nav.guides': 'Kilikili',
    'nav.accommodations': 'Sigi',
    'nav.gallery': 'Ja',
    'nav.agenda': 'Agenda',
    'nav.testimonials': 'Kuma',
    'nav.contact': 'Makari',
    'nav.explore': 'Sigi',
    'nav.login': 'Dugu',
    'nav.logout': 'Boli',
    'nav.myBookings': 'N reservations',
    'nav.admin': 'Admin',
    'hero.title': 'Casamance Hakili',
    'hero.subtitle': 'Sénégal kono',
    'hero.cta': 'Sigi léegi',
    'hero.book': 'Réserver',
    'booking.title': 'Réserver',
    'booking.name': 'I togo',
    'booking.email': 'Email',
    'booking.date': 'Kari',
    'booking.type': 'Baara suguya',
    'booking.region': 'Région',
    'booking.message': 'Kuma',
    'booking.submit': 'Sigi',
    'booking.guide': 'Guide',
    'booking.accommodation': 'Sigi',
    'booking.activity': 'Baara',
    'booking.gastronomy': 'Duminiya',
    'booking.discovery': 'Hakili',
    'auth.login': 'Dugu',
    'auth.register': 'Sigi',
    'auth.email': 'Email',
    'auth.password': 'Gundo',
    'auth.name': 'I togo',
    'auth.birthDate': 'Woloma kari',
    'auth.birthPlace': 'Woloma yoro',
    'auth.submit': 'Dugu',
    'auth.registerSubmit': 'Kont dila',
    'auth.forgotPassword': 'Gundo lekkat?',
    'auth.noAccount': 'Kont tew?',
    'auth.hasAccount': 'Kont be?',
    'activity.book': 'Réserver',
    'activity.duration': 'Waati',
    'activity.price': 'Juru',
    'guide.book': 'Guide réserver',
    'guide.languages': 'Kumakan',
    'guide.specialty': 'Baara',
    'accommodation.book': 'Réserver',
    'accommodation.features': 'Nyeta',
    'gastronomy.dishes': 'Duminiya',
    'gastronomy.drinks': 'Ji',
    'gastronomy.recipe': 'Sebe',
    'gastronomy.ingredients': 'Nyeta',
    'gallery.title': 'Galerie',
    'gallery.subtitle': 'Casamance rafet',
    'agenda.title': 'Agenda',
    'agenda.subtitle': 'Selidali',
    'testimonials.title': 'Kuma',
    'testimonials.subtitle': 'Kelenyaw kuma',
    'testimonials.addReview': 'Avis sigi',
    'contact.title': 'Makari',
    'contact.subtitle': 'An be yan',
    'contact.send': 'Ci',
    'admin.title': 'Admin',
    'admin.bookings': 'Réservations',
    'admin.media': 'Ja',
    'admin.users': 'Mow',
    'admin.config': 'Config',
    'common.loading': 'Ka di...',
    'common.error': 'Juru',
    'common.success': 'Aw!',
    'common.cancel': 'Bali',
    'common.confirm': 'Sigi',
    'common.close': 'Jara',
    'common.save': 'Mara',
    'common.all': 'Bé',
    'common.seeMore': 'Hakili',
    'common.book': 'Réserver',
    'common.back': 'Kogo',
    'footer.newsletter': 'Newsletter',
    'footer.newsletterText': 'Ka kanam taa',
    'footer.subscribe': 'Sigi',
    'footer.services': 'Baara',
    'footer.community': 'Jamaw',
    'footer.rights': 'Tëjj',
  },
  ff: {
    'nav.discover': 'Yiyande',
    'nav.visit': 'Yahde',
    'nav.activities': 'Golle',
    'nav.gastronomy': 'Ñaamdu',
    'nav.guides': 'Wowlude',
    'nav.accommodations': 'Jogorde',
    'nav.gallery': 'Tinnde',
    'nav.agenda': 'Agenda',
    'nav.testimonials': 'Haalaande',
    'nav.contact': 'Nodditaade',
    'nav.explore': 'Yiyande',
    'nav.login': 'Naatde',
    'nav.logout': 'Yaltude',
    'nav.myBookings': 'Am reservations',
    'nav.admin': 'Admin',
    'hero.title': 'Yiy Casamance',
    'hero.subtitle': 'Sénégal damal',
    'hero.cta': 'Yiy jooni',
    'hero.book': 'Réserver',
    'booking.title': 'Réserver',
    'booking.name': 'Innde maa',
    'booking.email': 'Email',
    'booking.date': 'Ñalawma',
    'booking.type': 'Golle',
    'booking.region': 'Région',
    'booking.message': 'Haalaande',
    'booking.submit': 'Setal',
    'booking.guide': 'Guide',
    'booking.accommodation': 'Jogorde',
    'booking.activity': 'Golle',
    'booking.gastronomy': 'Ñaamdu',
    'booking.discovery': 'Yiyande',
    'auth.login': 'Naatde',
    'auth.register': 'Bindude',
    'auth.email': 'Email',
    'auth.password': 'Sirlu',
    'auth.name': 'Innde maa',
    'auth.birthDate': 'Ñalawma dogngal',
    'auth.birthPlace': 'Laamorgo dogngal',
    'auth.submit': 'Naatde',
    'auth.registerSubmit': 'Kont waɗde',
    'auth.forgotPassword': 'Sirlu yiytaako?',
    'auth.noAccount': 'Kont alaa?',
    'auth.hasAccount': 'Kont woni?',
    'activity.book': 'Réserver',
    'activity.duration': 'Sahaa',
    'activity.price': 'Njamndi',
    'guide.book': 'Guide réserver',
    'guide.languages': 'Ɗemɗe',
    'guide.specialty': 'Golle',
    'accommodation.book': 'Réserver',
    'accommodation.features': 'Huunde',
    'gastronomy.dishes': 'Ñaamdu',
    'gastronomy.drinks': 'Ndiyam',
    'gastronomy.recipe': 'Tegirde',
    'gastronomy.ingredients': 'Huunde',
    'gallery.title': 'Galerie',
    'gallery.subtitle': 'Casamance rafet',
    'agenda.title': 'Agenda',
    'agenda.subtitle': 'Feere',
    'testimonials.title': 'Haalaande',
    'testimonials.subtitle': 'Jeyaaɓe haaldi',
    'testimonials.addReview': 'Avis haalde',
    'contact.title': 'Nodditaade',
    'contact.subtitle': 'Min ngoni',
    'contact.send': 'Neldu',
    'admin.title': 'Admin',
    'admin.bookings': 'Réservations',
    'admin.media': 'Tinnde',
    'admin.users': 'Jeyaaɓe',
    'admin.config': 'Config',
    'common.loading': 'Di warda...',
    'common.error': 'Moƴƴinaaki',
    'common.success': 'Moƴƴi!',
    'common.cancel': 'Haɓtude',
    'common.confirm': 'Setal',
    'common.close': 'Uddu',
    'common.save': 'Daano',
    'common.all': 'Fof',
    'common.seeMore': 'Yiyande',
    'common.book': 'Réserver',
    'common.back': 'Dogde',
    'footer.newsletter': 'Newsletter',
    'footer.newsletterText': 'Ka kanam',
    'footer.subscribe': 'Bindude',
    'footer.services': 'Golle',
    'footer.community': 'Jama',
    'footer.rights': 'Tëjj',
  },
};

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(
    (localStorage.getItem(LANG_KEY) as Language) || 'fr'
  );

  const setLang = (newLang: Language) => {
    localStorage.setItem(LANG_KEY, newLang);
    setLangState(newLang);
  };

  const t = (key: string) => {
    return translations[lang][key] || translations['fr'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useTranslation() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useTranslation must be used within LanguageProvider');
  return ctx;
}

