import type { Location, Activity, Guide, Accommodation, Dish, Drink, AgendaEvent, RegionDiscovery } from './types';

export const LOCATIONS: Location[] = [
  // Basse-Casamance
  {
    id: 'ziguinchor',
    name: 'Ziguinchor',
    region: 'Basse-Casamance',
    city: 'Ziguinchor',
    description: 'Capitale de la Casamance, ville historique aux ruelles colorées bordées de fromagers centenaires. Centre culturel animé avec marchés artisanaux et architecture coloniale portugaise.',
    image: 'https://tse3.mm.bing.net/th/id/OIP.ZBXPUYeh7i2pnflQsZqc-QHaFj?rs=1&pid=ImgDetMain&o=7&rm=3',
    category: 'Culture',
  },
  {
    id: 'cap-skirring',
    name: 'Cap Skirring',
    region: 'Basse-Casamance',
    city: 'Cap Skirring',
    description: 'Station balnéaire prisée avec ses plages de sable blanc et ses eaux turquoise. Paradis des surfeurs et des amoureux de la mer, offrant des couchers de soleil inoubliables.',
    image: 'https://th.bing.com/th/id/R.d553d84e83743476332baf4a20a4ce1e?rik=Ivf%2blfJNS3pOZg&riu=http%3a%2f%2fwww.cap-skirring.voyage%2fimages%2fhotel-luxe-cap-skirring-senegal.jpg%3fcrc%3d479439653&ehk=Q5ISp4xezekjnV9fYRnyjZMUANPIEPLe4k1nAYXCb6A%3d&risl=&pid=ImgRaw&r=0',
    category: 'Plage',
  },
  {
    id: 'karabane',
    name: 'Île de Karabane',
    region: 'Basse-Casamance',
    city: 'Karabane',
    description: "Île mystique à l'embouchure du fleuve Casamance. Vestiges de l'ancienne présence portugaise et française, avec une cathédrale abandonnée dans la jungle et une ambiance tors du temps.",
    image: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhIdIPOM469Ia3LAsnO0OcpLJ9HzkQrr6FxEh_h6ih518aIwdZj4VygyFjQd1AG_i5PtAmfSMWfLvMz8yIDGB9JZajwuvzoT8uLHXOxonMakdiOsCFR1mvMYyRNnvhpRpN6mwrvpgNtA7BF/s1600/ASPT2.jpg',
    category: 'Historique',
  },
  {
    id: 'cabrousse',
    name: 'Forêt de Cabrousse',
    region: 'Basse-Casamance',
    city: 'Cabrousse',
    description: "Forêt primaire luxuriante abritant une biodiversité exceptionnelle. Sentiers de randonnée à travers la canopée, observation d'oiseaux rares et rencontres avec les villages Diola traditionnels.",
    image: 'https://th.bing.com/th/id/R.0ea0f5052c65933a20bdbd9fd2783c04?rik=XDaccglXF9IKug&pid=ImgRaw&r=0',
    category: 'Nature',
  },
  {
    id: 'oussouye',
    name: 'Oussouye',
    region: 'Basse-Casamance',
    city: 'Oussouye',
    description: "Cœur de la culture Diola, cette ville abrite le palais du roi sacré d'Oussouye. Traditions animistes vivaces, cérémonies initiatiques et danses rituelles se mêlent à la vie quotidienne.",
    image: 'https://th.bing.com/th/id/OIP.gRpyEj7y64QhaxFHu_mo_AHaEK?w=308&h=180&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
    category: 'Culture',
  },
  {
    id: 'palmarin',
    name: 'Palmarin',
    region: 'Basse-Casamance',
    city: 'Palmarin',
    description: 'Village de pêcheurs authentique avec des plages sauvages et des lagunes de sel rose. Site de nidification de la sterne royale et paradis pour l\'observation des oiseaux migrateurs.',
    image: 'https://images.unsplash.com/photo-1509233725247-49e657c54213?w=800',
    category: 'Nature',
  },
  // Moyenne-Casamance
  {
    id: 'sedhiou',
    name: 'Sédhiou',
    region: 'Moyenne-Casamance',
    city: 'Sédhiou',
    description: 'Ville aux charmes cachés au bord du fleuve Casamance. Point de départ pour explorer les villages Mandingues et Peuls. Marché hebdomadaire coloré et hospitalité légendaire.',
    image: 'https://www.culture.gouv.sn/wp-content/uploads/2023/03/700F622E-5542-4D82-BE33-7DEEC7E1CA8D-1000x750.jpeg',
    category: 'Culture',
  },
  {
    id: 'kolda',
    name: 'Kolda',
    region: 'Moyenne-Casamance',
    city: 'Kolda',
    description: "Carrefour culturel peul, Kolda est connue pour son artisanat de cuir et ses troupeaux de zébus. La ville offre un aperçu authentique de la vie pastorale et des traditions nomades.",
    image: 'https://tse4.mm.bing.net/th/id/OIP.anePd_GBtzIcHwB9omYgAAHaE7?rs=1&pid=ImgDetMain&o=7&rm=3',
    category: 'Culture',
  },
  {
    id: 'parc-basse-casamance',
    name: 'Parc de la Basse-Casamance',
    region: 'Moyenne-Casamance',
    city: 'Oussouye',
    description: 'Réserve naturelle protégeant une forêt galerie remarquable. Habitat de buffles, phacochères, hyènes et nombreuses espèces d\'oiseaux. Safaris pédestres avec guides locaux expérimentés.',
    image: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800',
    category: 'Nature',
  },
  {
    id: 'goudomp',
    name: 'Goudomp',
    region: 'Moyenne-Casamance',
    city: 'Goudomp',
    description: 'Village perché au bord du fleuve, point de départ des excursions en pirogue. Marché aux poissons animé et traditions de pêche artisanale transmises de génération en génération.',
    image: 'https://th.bing.com/th/id/OIP.YkGL4HMKsJ0ATNL-JmeG9AHaE7?w=301&h=200&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
    category: 'Nature',
  },
  {
    id: 'simbandi',
    name: 'Simbandi Balante',
    region: 'Moyenne-Casamance',
    city: 'Simbandi',
    description: "Village traditionnel Balante préservé, où l'architecture en banco et les greniers à mil dessinent un paysage ancestral. Les habitants maintiennent des pratiques agricoles millénaires.",
    image: 'https://th.bing.com/th/id/OIP.wimIh6afdFyYHAn3kdkvKQHaEK?w=328&h=184&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
    category: 'Culture',
  },
  {
    id: 'marsassoum',
    name: 'Marsassoum',
    region: 'Moyenne-Casamance',
    city: 'Marsassoum',
    description: "Ancienne factorerie coloniale reconvertie en centre culturel. Musée de la Casamance retraçant l'histoire de la région depuis les royaumes précoloniaux jusqu'à l'indépendance.",
    image: 'https://tse2.mm.bing.net/th/id/OIP.mNLoruJ2_RaAo80-5PtRDQHaE7?rs=1&pid=ImgDetMain&o=7&rm=3',
    category: 'Historique',
  },
  // Haute-Casamance
  {
    id: 'velingara',
    name: 'Vélingara',
    region: 'Haute-Casamance',
    city: 'Vélingara',
    description: "Ville marchande à la croisée des cultures peule, mandingue et Diola. Porte d'entrée vers le parc du Niokolo-Koba et hub commercial pour les communautés rurales environnantes.",
    image: 'https://th.bing.com/th/id/OIP.aYj-O9Yc2r6L9_f-5KY_2AHaEK?w=333&h=187&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3',
    category: 'Culture',
  },
  {
    id: 'niokolo-koba',
    name: 'Parc du Niokolo-Koba',
    region: 'Haute-Casamance',
    city: 'Tambacounda',
    description: "Classé au patrimoine mondial de l'UNESCO, ce parc abrite lions, éléphants, hippopotames, chimpanzés et plus de 350 espèces d'oiseaux. Expérience safari unique en Afrique de l'Ouest.",
    image: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800',
    category: 'Nature',
  },
  {
    id: 'tambacounda',
    name: 'Tambacounda',
    region: 'Haute-Casamance',
    city: 'Tambacounda',
    description: "Ville-carrefour aux portes du Satel. Centre administratif et économique de la région orientale avec un marché aux bestiaux renommé et une cuisine locale savoureuse.",
    image: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800',
    category: 'Culture',
  },
  {
    id: 'wassadou',
    name: 'Wassadou',
    region: 'Haute-Casamance',
    city: 'Wassadou',
    description: "Village situé au cœur du parc du Niokolo-Koba. Observation des hippopotames dans leur habitat naturel au bord du fleuve Gambie et excursions de nuit pour apercevoir les prédateurs.",
    image: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800',
    category: 'Nature',
  },
  {
    id: 'diaoube',
    name: 'Diaoubé',
    region: 'Haute-Casamance',
    city: 'Diaoubé',
    description: "Site du plus grand marché hebdomadaire de la sous-région. Chaque jeudi, des milliers de commerçants convergent pour échanger bétail, textiles, épices et artisanat traditionnel.",
    image: 'https://tse3.mm.bing.net/th/id/OIP.jWr9MtsP2448mK4oib3H1AHaE7?rs=1&pid=ImgDetMain&o=7&rm=3',
    category: 'Culture',
  },
  {
    id: 'basse-gambie',
    name: 'Basse Gambie',
    region: 'Haute-Casamance',
    city: 'Saraya',
    description: "Confluence mystique du fleuve Gambie entourée de forêts galeries. Site arctéologique avec des cercles de pierres classés à l'UNESCO témoignant d'une civilisation ancienne.",
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
    category: 'Historique',
  },
];

export const ACTIVITIES: Activity[] = [
  // ── Sport (12) — Basse-Casamance ────────────────────────────
  { id: 's1',  name: 'Plaisirs Nautiques à Cap Skirring',   region: 'Basse-Casamance', description: 'Profitez de la mer cristalline de Cap Skirring pour une session de sports nautiques inoubliable : stand-up paddle, bouée tractée et snorkeling.', image: 'https://5afe5a211849786b420d348fdaea7d74.cdn.bubble.io/f1727184099796x367687588499140860/Photo%20Excursion%20-%202024-09-24T152021.565.png', price: 5000,  duration: '2h',   type: 'Sport' },
  { id: 's2',  name: 'Char à voile & Pêche sportive',        region: 'Basse-Casamance', description: 'Alliance adrénaline et tradition : glissez en char à voile sur la plage puis tentez votre chance avec les pêcheurs locaux pour une prise exceptionnelle.', image: 'https://i.pinimg.com/1200x/44/ca/66/44ca6684899a8492b3322c9d96183c29.jpg', price: 7000,  duration: '3h',   type: 'Sport' },
  { id: 's3',  name: 'Excursions Multi-sports VTT',           region: 'Basse-Casamance', description: 'Circuit multi-activités en VTT à travers pistes forestières, villages Diola et plages sauvages. Une expérience sportive tout-terrain incontournable.', image: 'https://www.casamancevtt.com/wp-content/uploads/2022/09/image.png', price: 9000,  duration: '4h',   type: 'Sport' },
  { id: 's4',  name: 'Randonnée cycliste',                    region: 'Basse-Casamance', description: 'Parcourez à vélo les routes ombragées de palmeraies et de mangroves de la Basse-Casamance, avec arrêts dans les villages pour rencontrer les habitants.', image: 'https://www.koldanews.com/wp-content/uploads/2024/11/IMG_20241121_180403-scaled.jpg', price: 11000, duration: '5h',   type: 'Sport' },
  { id: 's5',  name: 'Paddle',                                region: 'Basse-Casamance', description: 'Initiez-vous ou perfectionnez-vous au stand-up paddle sur les eaux calmes des bolons de Casamance. Location de planches et cours avec moniteur certifié.', image: 'https://www.au-senegal.com/IMG/webp/casamance_enchante6-2.webp', price: 13000, duration: '2h',   type: 'Sport' },
  { id: 's6',  name: 'Lutte sportive traditionnelle',         region: 'Basse-Casamance', description: 'Découvrez la lutte sénégalaise, sport national par excellence. Assistez à un combat entre champions locaux ou participez à une initiation ludique.', image: 'https://www.shutterstock.com/image-photo/senegal-september-19-men-traditional-260nw-189084812.jpg', price: 15000, duration: '2h30', type: 'Sport' },
  { id: 's7',  name: 'Pêche sportive en pirogue',             region: 'Basse-Casamance', description: 'Sortie en mer à bord d\'une pirogue motorisée pour une pêche sportive au large. Thiof, capitaine et barracuda au programme pour les plus chanceux.', image: 'https://www.au-senegal.com/local/cache-vignettes/L650xH341/60a45d5f732b57a9bfce7abdbd030f-181e0.jpg', price: 17000, duration: '5h',   type: 'Sport' },
  { id: 's8',  name: 'Ski nautique',                          region: 'Basse-Casamance', description: 'Glissez sur les eaux chaudes de l\'Atlantique avec un moniteur expérimenté. Initiation et perfectionnement en ski nautique et wakeboard.', image: 'https://tse4.mm.bing.net/th/id/OIP.u7pI7TYtfmh2ayK_0W86mgHaE8?rs=1&pid=ImgDetMain&o=7&rm=3', price: 19000, duration: '1h30', type: 'Sport' },
  { id: 's9',  name: 'Casamance VTT',                         region: 'Basse-Casamance', description: 'Grand circuit VTT de la Basse-Casamance : pistes techniques, traversées de bolons en pirogue-vélo et découverte des écosystèmes forestiers.', image: 'https://tse1.explicit.bing.net/th/id/OIP.VHyqkAn1oGBi-5eCgZNBdAHaFj?rs=1&pid=ImgDetMain&o=7&rm=3', price: 21000, duration: '6h',   type: 'Sport' },
  { id: 's10', name: 'Randonnée Trekking',                    region: 'Basse-Casamance', description: 'Trek à travers les forêts de palétuviers et les palmeraies de la Basse-Casamance. Observation des oiseaux migrateurs et bain dans les sources naturelles.', image: 'https://tse4.mm.bing.net/th/id/OIP.RrXSzjD0vtZnC3cukPQtOQHaE8?rs=1&pid=ImgDetMain&o=7&rm=3', price: 23000, duration: '7h',   type: 'Sport' },
  { id: 's11', name: 'Course en Pirogue',                     region: 'Basse-Casamance', description: 'Participez à l\'emblématique course de pirogues traditionnelles sur le fleuve Casamance. Ambiance festive garantie avec les pêcheurs Diola.', image: 'https://tse2.mm.bing.net/th/id/OIP.PENsT_GWx8yK-rXSrb3_8AHaEK?rs=1&pid=ImgDetMain&o=7&rm=3', price: 25000, duration: '3h',   type: 'Sport' },
  { id: 's12', name: 'Surf des marées',                       region: 'Basse-Casamance', description: 'Surfez les vagues créées par les marées montantes dans les canaux de mangrove. Une expérience unique et confidentielle connue des seuls locaux.', image: 'https://tse2.mm.bing.net/th/id/OIP.otYGMqszeQvc1nmE2y7N5gHaD4?rs=1&pid=ImgDetMain&o=7&rm=3', price: 27000, duration: '3h',   type: 'Sport' },

  // ── Culture (12) — régions mixtes ───────────────────────────
  { id: 'c1',  name: 'Découverte Villages Traditionnels',     region: 'Basse-Casamance', description: 'Immersion complète dans la vie quotidienne des villages Diola. Rencontre avec les anciens, participation aux travaux agricoles et dégustation de la cuisine locale.', image: 'https://discover-senegal.com/wp-content/uploads/2019/10/Les-Dioulas.jpg', price: 5000,  duration: '4h',   type: 'Culture' },
  { id: 'c2',  name: 'Kankourang',                            region: 'Moyenne-Casamance', description: 'Assistez à la manifestation du Kankourang, esprit protecteur des initiés en Mandingue. Classé au patrimoine immatériel de l\'UNESCO, un spectacle fascinant.', image: 'https://casamanceaupresent.com/wp-content/uploads/2017/09/Culture-Diola.jpg', price: 7000,  duration: '3h',   type: 'Culture' },
  { id: 'c3',  name: 'Musées et Sites historiques',           region: 'Basse-Casamance', description: 'Circuit des musées et sites patrimoniaux de Ziguinchor : musée régional, ancienne factorerie portugaise et mémorial du naufrage du Joola.', image: 'https://kumakonda.es/wp-content/uploads/2024/05/Casamance-7.jpg.webp', price: 9000,  duration: '5h',   type: 'Culture' },
  { id: 'c4',  name: 'Festivals récurrents locaux',           region: 'Basse-Casamance', description: 'Participation aux festivals saisonniers : fête du Casséou, fête du mil, cérémonies de récolte. Musique live, danse et gastronomie festive.', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_xZuyWbzS_V_WGBztV0TE11WCQxiCgyvhHA&s', price: 11000, duration: '6h',   type: 'Culture' },
  { id: 'c5',  name: 'Cérémonie et partage',                  region: 'Basse-Casamance', description: 'Soyez l\'invité d\'honneur d\'une cérémonie traditionnelle Diola. Repas communautaire autour du vin de palme, kola et danses rituelles.', image: 'https://images.ladepeche.fr/api/v1/images/view/5e17fad83e454620cc117750/large/image.jpg?v=1', price: 13000, duration: '4h',   type: 'Culture' },
  { id: 'c6',  name: 'Circoncision traditionnelle',           region: 'Basse-Casamance', description: 'Observation (non-participante) des rites de passage liés à la circoncision chez les Diola. Un rituel initiatique millénaire au cœur de la culture.', image: 'https://casamanceaupresent.com/wp-content/uploads/2025/06/WhatsApp-Image-2025-06-16-at-10.37.40-1024x1013.jpeg', price: 15000, duration: '5h',   type: 'Culture' },
  { id: 'c7',  name: 'Festivals Diolas (Boukout)',            region: 'Basse-Casamance', description: 'Le Boukout, grand rassemblement initiatique Diola qui se tient tous les 20 ans. Une chance rare d\'assister à l\'un des rituels les plus secrets d\'Afrique.', image: 'https://i.ytimg.com/vi/aQQukBBed7c/hq720.jpg?sqp=-oaymwE8CK4FEIIDSFryq4qpAy0IARUAAAAAGAElAADIQj0AgKJD8AEB-AH-CYAC0AWKAgwIABABGIwBIFEoFTAP&rs=AOn4CLB6bNvg5ac-nf4RWTfJ6c8y44_9sg', price: 17000, duration: '8h',   type: 'Culture' },
  { id: 'c8',  name: 'Art sacré',                             region: 'Basse-Casamance', description: 'Découvrez l\'art sacré Diola : statuettes Ankoe, masques de danse et objets rituels conservés dans les sanctuaires villageois. Visite guidée par un prêtre Diola.', image: 'https://www.koldanews.com/wp-content/uploads/2024/03/filles.jpg', price: 19000, duration: '3h',   type: 'Culture' },
  { id: 'c9',  name: 'Femme du bois sacré',                   region: 'Basse-Casamance', description: 'Rencontrez les gardiennes des bois sacrés féminins de Casamance. Ces femmes sont les dépositaires des savoirs botaniques et spirituels ancestraux.', image: 'https://www.koldanews.com/wp-content/uploads/2017/09/circoncis.jpg', price: 21000, duration: '4h',   type: 'Culture' },
  { id: 'c10', name: 'Musée Kadioute',                        region: 'Basse-Casamance', description: 'Visite approfondie du musée de Kadioute, sanctuaire des arts et traditions Diola. Collection unique de masques, fétiches et instruments de musique.', image: 'https://sunugox.info/wp-content/uploads/2024/12/IMG_4218.jpeg', price: 23000, duration: '2h30', type: 'Culture' },
  { id: 'c11', name: 'Edioungou (poterie)',                   region: 'Basse-Casamance', description: 'Initiation à la poterie traditionnelle Diola dans le village d\'Edioungou. Façonnez votre propre pièce selon les techniques ancestrales transmises de mère en fille.', image: 'https://c8.alamy.com/compfr/bpy0p4/l-artisanat-au-marche-artisanal-ziguinchor-casamance-senegal-bpy0p4.jpg', price: 25000, duration: '3h',   type: 'Culture' },
  { id: 'c12', name: 'Rencontre du roi bolong',               region: 'Basse-Casamance', description: 'Audience exceptionnelle avec le roi des bolons, gardien des traditions fluviales de la Basse-Casamance. Une rencontre rare et profondément émouvante.', image: 'https://senego.com/wp-content/uploads/2025/11/577759418_844587578396556_3934638099937196966_n-1-1024x1024.jpg', price: 27000, duration: '4h',   type: 'Culture' },

  // ── Nature (12) — régions mixtes ────────────────────────────
  { id: 'n1',  name: 'Safaris Réserves Niokolo-Koba',         region: 'Basse-Casamance', description: 'Safari dans les réserves naturelles protégées de Casamance. Hippopotames, singes rouges et centaines d\'espèces d\'oiseaux dans leur habitat naturel.', image: 'https://tse1.mm.bing.net/th/id/OIP.OkxoULCzkwQAkK0Xs6GdjQHaE0?rs=1&pid=ImgDetMain&o=7&rm=3', price: 5000,  duration: '6h',   type: 'Nature' },
  { id: 'n2',  name: 'Eco-parc de Diembering',                region: 'Basse-Casamance', description: 'Explorez l\'éco-parc de Diembering, sanctuaire de biodiversité unique : forêts primaires, serpents de mer et tortues marines sur la plage voisine.', image: 'https://capnature.eu/wp-content/uploads/2022/03/ski-nautique-1-1.png', price: 7000,  duration: '4h',   type: 'Nature' },
  { id: 'n3',  name: 'Karabane (îles aux oiseaux)',           region: 'Basse-Casamance', description: 'Excursion en pirogue vers les îles ornithologiques de Karabane. Plus de 200 espèces nichent ici : hérons, sternes, pélicans et flamants roses.', image: 'https://journals.openedition.org/eps/docannexe/image/8250/img-3-small580.jpg', price: 9000,  duration: '5h',   type: 'Nature' },
  { id: 'n4',  name: 'Fleuve Casamance',                      region: 'Basse-Casamance', description: 'Croisière contemplative sur le fleuve Casamance au coucher du soleil. Bancs de dauphins, hippopotames et pêcheurs sur pirogues colorées.', image: 'https://www.ecofund.org/upload/images/news/l/Casamance_Ecoparc_Inauguration_05.07.2013_47_1_1.jpg', price: 11000, duration: '3h',   type: 'Nature' },
  { id: 'n5',  name: 'Balade en pirogue',                     region: 'Basse-Casamance', description: 'Remontée en pirogue silencieuse dans les bolons sacrés de Casamance. Une expérience mélancolique et apaisante au cœur des mangroves.', image: 'https://www.guidesulysse.com/imageswebp/destinations/iStock-965488648.webp', price: 13000, duration: '3h',   type: 'Nature' },
  { id: 'n6',  name: 'Découverte faune',                      region: 'Basse-Casamance', description: 'Sortie naturaliste avec un biologiste local pour identifier les espèces emblématiques : lamantin du fleuve, singe rouge, calao terrestre.', image: 'https://gizc.org/wp-content/uploads/2020/03/2002070445v-c-s-e1583766214289.jpg', price: 15000, duration: '4h',   type: 'Nature' },
  { id: 'n7',  name: 'Immersion Bolongs',                     region: 'Haute-Casamance', description: 'Immersion totale dans le réseau de bolons de la Haute-Casamance. Campement flottant, pêche nocturne et lever de soleil sur les mangroves dorées.', image: 'https://assets-global.website-files.com/662f675c562af034c9124b98/664d9430dee99b3d57a3f776_IMG_1001.webp', price: 17000, duration: '16h',  type: 'Nature' },
  { id: 'n8',  name: 'Eco-randonnée',                         region: 'Haute-Casamance', description: 'Randonnée éco-responsable guidée par un pisteur Bassari dans les forêts galeries de Haute-Casamance. Identification des plantes médicinales.', image: 'https://mycasamance.com/wp-content/uploads/2021/09/UNE-FAUNE-ET-DES-ESPECES-ORNITHOLOGIQUES-VARIEES-PICTURE-40.jpg', price: 19000, duration: '6h',   type: 'Nature' },
  { id: 'n9',  name: 'Observation des dauphins',              region: 'Basse-Casamance', description: 'Sortie en mer pour observer les dauphins à bosse de l\'Atlantique qui jouent régulièrement à l\'embouchure du fleuve Casamance.', image: 'https://www.senactu24.info/wp-content/uploads/2024/10/images-1.jpeg', price: 21000, duration: '4h',   type: 'Nature' },
  { id: 'n10', name: 'Mangrove mystique',                     region: 'Basse-Casamance', description: 'Exploration nocturne des mangroves bioluminescentes de Casamance. Un spectacle féerique unique au monde où l\'eau brille de mille feux dans l\'obscurité.', image: 'https://static.dw.com/image/15980597_605.jpg', price: 23000, duration: '3h',   type: 'Nature' },
  { id: 'n11', name: 'Sentiers botaniques',                   region: 'Basse-Casamance', description: 'Parcours botanique guidé par un ethnobotaniste dans les forêts de Casamance. Plantes médicinales, épices sauvages et arbres à valeur culturelle.', image: 'https://www.echoscommunication.org/wp-content/uploads/2025/10/Humeubeul01-1024x768.jpg', price: 25000, duration: '4h',   type: 'Nature' },
  { id: 'n12', name: 'Faune marine',                          region: 'Basse-Casamance', description: 'Plongée en apnée ou avec masque dans les eaux cristallines de Cap Skirring. Raies, mérous colorés et coraux découverts avec un moniteur certifié.', image: 'https://au-senegal.com/IMG/jpg/canoe-2.jpg', price: 27000, duration: '3h',   type: 'Nature' },
];

export const GUIDES: Guide[] = [
  {
    id: 'guide-1',
    name: 'Jean Philip Bassene',
    region: 'Basse-Casamance',
    languages: ['Français', 'Wolof', 'Anglais', 'Diola'],
    specialty: ["Nature","Écotourisme","Ornithologie"],
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHU6iUAsUv3RTQWAg54o6HHvK6gxIzz7BAwQ&s',
    experience: "5 ans d'expérience",
    bio: 'Passionné par la biodiversité des mangroves et des bolons, Jean Philip guide ses clients vers les espèces rares que seuls les locaux connaissent.',
    rating: 4.9,
    reviewCount: 127,
  },
  {
    id: 'guide-2',
    name: 'Pierre Sambou',
    region: 'Basse-Casamance',
    languages: ['Français', 'Diola', 'Anglais'],
    specialty: ["Culture","Art sacré","Villages Diola"],
    image: 'https://guideyourtrip.com/wp-content/uploads/2024/02/guide-senegal-pierre-sambou.jpg',
    experience: "6 ans d'expérience",
    bio: "Descendant d'une longue lignée de griots Diola, Pierre transmet les secrets de sa culture avec une passion communicative.",
    rating: 4.8,
    reviewCount: 89,
  },
  {
    id: 'guide-3',
    name: 'Isidore Akibo Diatta',
    region: 'Basse-Casamance',
    languages: ['Français', 'Diola', 'Espagnol'],
    specialty: ["Nature","Forêts sacrées","Faune sauvage"],
    image: 'https://guideyourtrip.com/wp-content/uploads/2023/10/guide-senegal-isidore-akibo-diatta.jpg',
    experience: "6 ans d'expérience",
    bio: 'Biologiste de terrain, Isidore a cartographié la faune et la flore de la Basse-Casamance. Une encyclopédie vivante de la nature locale.',
    rating: 4.9,
    reviewCount: 203,
  },
  {
    id: 'guide-4',
    name: 'Boubacar Cisse',
    region: 'Moyenne-Casamance',
    languages: ['Français', 'Mandingue', 'Anglais'],
    specialty: ["Sport","Randonnée","Pirogue"],
    image: 'https://guideyourtrip.com/wp-content/uploads/2023/10/guide-senegal-boubakar-cisse.jpg',
    experience: "4 ans d'expérience",
    bio: 'Ex-champion régional de kayak, Boubacar organise des circuits sportifs sur mesure à travers les bolons et les forêts galeries de Moyenne-Casamance.',
    rating: 4.7,
    reviewCount: 64,
  },
  {
    id: 'guide-5',
    name: 'Joel Diatta',
    region: 'Basse-Casamance',
    languages: ['Français', 'Wolof', 'Anglais'],
    specialty: ["Culture","Histoire coloniale","Patrimoine"],
    image: 'https://guideyourtrip.com/wp-content/uploads/2023/11/guide-senegal-joel-diatta.webp',
    experience: "7 ans d'expérience",
    bio: 'Historien passionné et guide certifié, Joel emmène ses visiteurs dans les lieux historiques de Ziguinchor et des îles avec une narration captivante.',
    rating: 4.8,
    reviewCount: 52,
  },
  {
    id: 'guide-6',
    name: 'Salif Diallo',
    region: 'Haute-Casamance',
    languages: ['Français', 'Peult', 'Espagnol'],
    specialty: ['Nature', 'Safari', 'Niokolo-Koba'],
    image: 'https://5afe5a211849786b420d348fdaea7d74.cdn.bubble.io/cdn-cgi/image/w=384,h=384,f=auto,dpr=1.5,fit=contain/f1702304215951x417759787327301400/Guide%20%2850%29.png',
    experience: '3 ans d\'expérience',
    bio: 'Pisteur de talent formé au parc du Niokolo-Koba, Salif a grandi en brousse au milieu des animaux sauvages. Sa connaissance du terrain est sans égale.',
    rating: 4.6,
    reviewCount: 41,
  },
  {
    id: 'guide-7',
    name: 'Omar Mané',
    region: 'Moyenne-Casamance',
    languages: ['Français', 'Anglais', 'Mandingue'],
    specialty: ['Nature', 'Biodiversité', 'Faune forestière'],
    image: 'https://5afe5a211849786b420d348fdaea7d74.cdn.bubble.io/cdn-cgi/image/w=384,h=384,f=auto,dpr=1.5,fit=contain/f1719235820768x906551349415056400/Guide%20%2813%29.png',
    experience: '4 ans d\'expérience',
    bio: 'Spécialiste des bois sacrés et des plantes médicinales, Omar initie ses clients aux secrets botaniques de la Moyenne-Casamance.',
    rating: 5.0,
    reviewCount: 312,
  },
  {
    id: 'guide-8',
    name: 'Abdoulaye Diop',
    region: 'Haute-Casamance',
    languages: ['Français', 'Anglais', 'Peult'],
    specialty: ['Culture', 'Artisanat Peul', 'Traditions Fouladou'],
    image: 'https://5afe5a211849786b420d348fdaea7d74.cdn.bubble.io/cdn-cgi/image/w=384,h=384,f=auto,dpr=1.5,fit=contain/f1681303285769x181460361521952770/Guide%20%281%29.png',
    experience: '5 ans d\'expérience',
    bio: 'Gardien des traditions du Fouladou, Abdoulaye organise des séjours d\'immersion chez les éleveurs Peuls et dans les marchés traditionnels.',
    rating: 4.8,
    reviewCount: 78,
  },
  {
    id: 'guide-9',
    name: 'Moussa Sané',
    region: 'Moyenne-Casamance',
    languages: ['Français', 'Wolof', 'Mandingue'],
    specialty: ['Culture', 'Kankourang', 'Griots'],
    image: 'https://5afe5a211849786b420d348fdaea7d74.cdn.bubble.io/cdn-cgi/image/w=384,h=384,f=auto,dpr=1.5,fit=contain/f1672865951325x262380053466145570/Olivier%20%28Se%CC%81ne%CC%81gal%29.png',
    experience: '4 ans d\'expérience',
    bio: 'Fils de griot et musicien de kora, Moussa partage les légendes et l\'histoire des royaumes mandingues avec une éloquence rare.',
    rating: 4.9,
    reviewCount: 156,
  },
];
export const ACCOMMODATIONS: Accommodation[] = [
  { id: 'hotel-0', name: 'Hotel Le Perroquet-Ziguinchor', region: 'Basse-Casamance', type: 'Hôtel', priceRange: 'A partir de 15 000 FCFA', images: ['https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2b/37/20/f8/caption.jpg?w=600&h=-1&s=1', 'https://picsum.photos/seed/acc-hôtel-0-1/800/600', 'https://picsum.photos/seed/acc-hôtel-0-2/800/600', 'https://picsum.photos/seed/acc-hôtel-0-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 4, description: 'Hébergement Hôtel de qualité en Basse-Casamance, alliant confort moderne et charme local.' },
  { id: 'hotel-1', name: 'Hôtel Kadiandoumagne-Ziguinchor', region: 'Basse-Casamance', type: 'Hôtel', priceRange: 'A partir de 20 000 FCFA', images: ['https://cdn-zen.readytotrip.com/t/1024x768/content/a1/dc/a1dceb56a5f0f7c328efe510f44d6cd5b1d8cab2.jpeg', 'https://picsum.photos/seed/acc-hôtel-1-1/800/600', 'https://picsum.photos/seed/acc-hôtel-1-2/800/600', 'https://picsum.photos/seed/acc-hôtel-1-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 5, description: 'Hébergement Hôtel de qualité en Basse-Casamance, alliant confort moderne et charme local.' },
  { id: 'hotel-2', name: 'HOTEL AUBERT-Ziguinchor', region: 'Basse-Casamance', type: 'Hôtel', priceRange: 'A partir de 25 000 FCFA', images: ['https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/ae/c4/80/hotel-aubert.jpg?w=900&h=500&s=1', 'https://picsum.photos/seed/acc-hôtel-2-1/800/600', 'https://picsum.photos/seed/acc-hôtel-2-2/800/600', 'https://picsum.photos/seed/acc-hôtel-2-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 4, description: 'Hébergement Hôtel de qualité en Basse-Casamance, alliant confort moderne et charme local.' },
  { id: 'hotel-3', name: 'Hotel Le Firdou-Kolda', region: 'Haute-Casamance', type: 'Hôtel', priceRange: 'A partir de 30 000 FCFA', images: ['https://www.au-senegal.com/local/cache-gd2/3f/e8440a8a016312dc979e613997a470.jpg?1742903739', 'https://picsum.photos/seed/acc-hôtel-3-1/800/600', 'https://picsum.photos/seed/acc-hôtel-3-2/800/600', 'https://picsum.photos/seed/acc-hôtel-3-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 5, description: 'Hébergement Hôtel de qualité en Haute-Casamance, alliant confort moderne et charme local.' },
  { id: 'hotel-4', name: 'Hotel Le Flamboyant-Ziguinchor', region: 'Basse-Casamance', type: 'Hôtel', priceRange: 'A partir de 35 000 FCFA', images: ['https://static-cf.readytotrip.com/upload/information_system_24/1/6/1/item_1612058/photo_22434081.jpg', 'https://picsum.photos/seed/acc-hôtel-4-1/800/600', 'https://picsum.photos/seed/acc-hôtel-4-2/800/600', 'https://picsum.photos/seed/acc-hôtel-4-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 4, description: 'Hébergement Hôtel de qualité en Basse-Casamance, alliant confort moderne et charme local.' },
  { id: 'hotel-5', name: 'Hotel Motel Le Regal-CAP SKIRRING', region: 'Basse-Casamance', type: 'Hôtel', priceRange: 'A partir de 40 000 FCFA', images: ['https://i.travelapi.com/lodging/35000000/35000000/34992500/34992412/b4d56af0_z.jpg', 'https://picsum.photos/seed/acc-hôtel-5-1/800/600', 'https://picsum.photos/seed/acc-hôtel-5-2/800/600', 'https://picsum.photos/seed/acc-hôtel-5-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 5, description: 'Hébergement Hôtel de qualité en Basse-Casamance, alliant confort moderne et charme local.' },
  { id: 'hotel-6', name: 'Hotel du Palmier', region: 'Haute-Casamance', type: 'Hôtel', priceRange: 'A partir de 45 000 FCFA', images: ['https://www.voyagesaquaterra.com/club-med-cap-skirring-senegal-4-fr.jpg', 'https://picsum.photos/seed/acc-hôtel-6-1/800/600', 'https://picsum.photos/seed/acc-hôtel-6-2/800/600', 'https://picsum.photos/seed/acc-hôtel-6-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 4, description: 'Hébergement Hôtel de qualité en Haute-Casamance, alliant confort moderne et charme local.' },
  { id: 'hotel-7', name: 'Hotel de la Mangrove', region: 'Moyenne-Casamance', type: 'Hôtel', priceRange: 'A partir de 50 000 FCFA', images: ['https://dynamic-media-cdn.tripadvisor.com/media/photo-o/09/a3/dd/25/bijilo.jpg?w=900&h=500&s=1', 'https://picsum.photos/seed/acc-hôtel-7-1/800/600', 'https://picsum.photos/seed/acc-hôtel-7-2/800/600', 'https://picsum.photos/seed/acc-hôtel-7-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 5, description: 'Hébergement Hôtel de qualité en Moyenne-Casamance, alliant confort moderne et charme local.' },
  { id: 'hotel-8', name: 'Hotel du Bolong', region: 'Haute-Casamance', type: 'Hôtel', priceRange: 'A partir de 55 000 FCFA', images: ['https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/55/ef/98/photo2jpg.jpg?w=900&h=500&s=1', 'https://picsum.photos/seed/acc-hôtel-8-1/800/600', 'https://picsum.photos/seed/acc-hôtel-8-2/800/600', 'https://picsum.photos/seed/acc-hôtel-8-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 4, description: 'Hébergement Hôtel de qualité en Haute-Casamance, alliant confort moderne et charme local.' },
  { id: 'hotel-9', name: 'Hotel Le Bantabatoo-Sédhiou', region: 'Moyenne-Casamance', type: 'Hôtel', priceRange: 'A partir de 60 000 FCFA', images: ['https://www.banta-batoo-lodge.com/IMG/jpg/banta_baatoo_lodge_sedhiou_1_.jpg', 'https://picsum.photos/seed/acc-hôtel-9-1/800/600', 'https://picsum.photos/seed/acc-hôtel-9-2/800/600', 'https://picsum.photos/seed/acc-hôtel-9-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 5, description: 'Hébergement Hôtel de qualité en Moyenne-Casamance, alliant confort moderne et charme local.' },
  { id: 'hotel-10', name: 'Hôtel Le Relais de Kolda', region: 'Haute-Casamance', type: 'Hôtel', priceRange: 'A partir de 65 000 FCFA', images: ['https://cf.bstatic.com/xdata/images/hotel/max1024x768/420289436.jpg?k=ffe87454d47c945a198718a8606530d16a1a1111c7c0cf9d7f0e71c709d71616&o=', 'https://picsum.photos/seed/acc-hôtel-10-1/800/600', 'https://picsum.photos/seed/acc-hôtel-10-2/800/600', 'https://picsum.photos/seed/acc-hôtel-10-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 4, description: 'Hébergement Hôtel de qualité en Haute-Casamance, alliant confort moderne et charme local.' },
  { id: 'hotel-11', name: 'Hotel-Sédhiou', region: 'Moyenne-Casamance', type: 'Hôtel', priceRange: 'A partir de 70 000 FCFA', images: ['https://dynamic-media-cdn.tripadvisor.com/media/photo-o/31/dc/af/22/view-from-the-ocean.jpg?w=1200&h=-1&s=1', 'https://picsum.photos/seed/acc-hôtel-11-1/800/600', 'https://picsum.photos/seed/acc-hôtel-11-2/800/600', 'https://picsum.photos/seed/acc-hôtel-11-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 5, description: 'Hébergement Hôtel de qualité en Moyenne-Casamance, alliant confort moderne et charme local.' },
  { id: 'camp-0', name: 'Campement du Fleuve', region: 'Basse-Casamance', type: 'Campement', priceRange: 'A partir de 15 000 FCFA', images: ['https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0a/2f/91/39/campement-solidaire-de.jpg?w=1200&h=-1&s=1', 'https://picsum.photos/seed/acc-campement-0-1/800/600', 'https://picsum.photos/seed/acc-campement-0-2/800/600', 'https://picsum.photos/seed/acc-campement-0-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 4, description: 'Hébergement Campement de qualité en Basse-Casamance, alliant confort moderne et charme local.' },
  { id: 'camp-1', name: 'Campement de la Plage', region: 'Moyenne-Casamance', type: 'Campement', priceRange: 'A partir de 20 000 FCFA', images: ['https://q-xx.bstatic.com/xdata/images/hotel/max1920x1080/511874559.webp?k=de6c7160fcca323c9767e9b7dd6404acad663a30cdbef8b33ac3708878e07ec2&o=', 'https://picsum.photos/seed/acc-campement-1-1/800/600', 'https://picsum.photos/seed/acc-campement-1-2/800/600', 'https://picsum.photos/seed/acc-campement-1-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 5, description: 'Hébergement Campement de qualité en Moyenne-Casamance, alliant confort moderne et charme local.' },
  { id: 'camp-2', name: 'Campement du Roi', region: 'Haute-Casamance', type: 'Campement', priceRange: 'A partir de 25 000 FCFA', images: ['https://q-xx.bstatic.com/xdata/images/hotel/max500/750486183.jpg?k=1ab4f95871d3552aefa0c86779e0034d756085c269ee09e4494e35dc6f6a0238&o=', 'https://picsum.photos/seed/acc-campement-2-1/800/600', 'https://picsum.photos/seed/acc-campement-2-2/800/600', 'https://picsum.photos/seed/acc-campement-2-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 4, description: 'Hébergement Campement de qualité en Haute-Casamance, alliant confort moderne et charme local.' },
  { id: 'camp-3', name: 'Campement Soleil', region: 'Basse-Casamance', type: 'Campement', priceRange: 'A partir de 30 000 FCFA', images: ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR50LLy3-_U5nIgV-YAvzeAOBTvzVw3n9OD8g&s', 'https://picsum.photos/seed/acc-campement-3-1/800/600', 'https://picsum.photos/seed/acc-campement-3-2/800/600', 'https://picsum.photos/seed/acc-campement-3-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 5, description: 'Hébergement Campement de qualité en Basse-Casamance, alliant confort moderne et charme local.' },
  { id: 'camp-4', name: 'Campement Escale', region: 'Moyenne-Casamance', type: 'Campement', priceRange: 'A partir de 35 000 FCFA', images: ['https://www.au-senegal.com/IMG/jpg/la-palmeraie_2_.jpg', 'https://picsum.photos/seed/acc-campement-4-1/800/600', 'https://picsum.photos/seed/acc-campement-4-2/800/600', 'https://picsum.photos/seed/acc-campement-4-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 4, description: 'Hébergement Campement de qualité en Moyenne-Casamance, alliant confort moderne et charme local.' },
  { id: 'camp-5', name: 'Campement Teranga', region: 'Haute-Casamance', type: 'Campement', priceRange: 'A partir de 40 000 FCFA', images: ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSF4V_blkibsSkD-70mfQ10LIf19e7XYztXEA&s', 'https://picsum.photos/seed/acc-campement-5-1/800/600', 'https://picsum.photos/seed/acc-campement-5-2/800/600', 'https://picsum.photos/seed/acc-campement-5-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 5, description: 'Hébergement Campement de qualité en Haute-Casamance, alliant confort moderne et charme local.' },
  { id: 'camp-6', name: 'Campement Palmier', region: 'Basse-Casamance', type: 'Campement', priceRange: 'A partir de 45 000 FCFA', images: ['https://www.au-senegal.com/IMG/jpg/ad901002017eb5db675b5c3b1f219dc3.jpg', 'https://picsum.photos/seed/acc-campement-6-1/800/600', 'https://picsum.photos/seed/acc-campement-6-2/800/600', 'https://picsum.photos/seed/acc-campement-6-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 4, description: 'Hébergement Campement de qualité en Basse-Casamance, alliant confort moderne et charme local.' },
  { id: 'camp-7', name: 'Campement Mangrove', region: 'Moyenne-Casamance', type: 'Campement', priceRange: 'A partir de 50 000 FCFA', images: ['https://cf.bstatic.com/xdata/images/hotel/max500/350981497.jpg?k=02da1ef5fe69fab5f8dc6ecc0f5bea45de69218b978f524357e035f99fc270b2&o=&hp=1', 'https://picsum.photos/seed/acc-campement-7-1/800/600', 'https://picsum.photos/seed/acc-campement-7-2/800/600', 'https://picsum.photos/seed/acc-campement-7-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 5, description: 'Hébergement Campement de qualité en Moyenne-Casamance, alliant confort moderne et charme local.' },
  { id: 'camp-8', name: 'Campement Bolong', region: 'Haute-Casamance', type: 'Campement', priceRange: 'A partir de 55 000 FCFA', images: ['https://dynamic-media-cdn.tripadvisor.com/media/photo-o/09/6e/fc/58/camping-casamance.jpg?w=900&h=500&s=1', 'https://picsum.photos/seed/acc-campement-8-1/800/600', 'https://picsum.photos/seed/acc-campement-8-2/800/600', 'https://picsum.photos/seed/acc-campement-8-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 4, description: 'Hébergement Campement de qualité en Haute-Casamance, alliant confort moderne et charme local.' },
  { id: 'camp-9', name: 'Campement Evasion', region: 'Basse-Casamance', type: 'Campement', priceRange: 'A partir de 60 000 FCFA', images: ['https://www.au-senegal.com/local/cache-vignettes/L600xH315/2368c9a792a0164b1a83d69f8c6d40-1f96a.jpg', 'https://picsum.photos/seed/acc-campement-9-1/800/600', 'https://picsum.photos/seed/acc-campement-9-2/800/600', 'https://picsum.photos/seed/acc-campement-9-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 5, description: 'Hébergement Campement de qualité en Basse-Casamance, alliant confort moderne et charme local.' },
  { id: 'camp-10', name: 'Campement Sérénité', region: 'Moyenne-Casamance', type: 'Campement', priceRange: 'A partir de 65 000 FCFA', images: ['https://dynamic-media-cdn.tripadvisor.com/media/photo-o/21/74/f4/ff/l-entree-du-campement.jpg?w=1200&h=-1&s=1', 'https://picsum.photos/seed/acc-campement-10-1/800/600', 'https://picsum.photos/seed/acc-campement-10-2/800/600', 'https://picsum.photos/seed/acc-campement-10-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 4, description: 'Hébergement Campement de qualité en Moyenne-Casamance, alliant confort moderne et charme local.' },
  { id: 'camp-11', name: 'Campement Authentique', region: 'Haute-Casamance', type: 'Campement', priceRange: 'A partir de 70 000 FCFA', images: ['https://cdn.hotelsmotor.com/255/25487/Campement_Kunja_Kafoutine-Ziguinchor-Senegal13_large.webp', 'https://picsum.photos/seed/acc-campement-11-1/800/600', 'https://picsum.photos/seed/acc-campement-11-2/800/600', 'https://picsum.photos/seed/acc-campement-11-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 5, description: 'Hébergement Campement de qualité en Haute-Casamance, alliant confort moderne et charme local.' },
  { id: 'eco-0', name: 'Éco-Lodge du Fleuve', region: 'Basse-Casamance', type: 'Éco-Lodge', priceRange: 'A partir de 15 000 FCFA', images: ['https://www.lepapayer.com/pictures/ecolodge-le-papayer-5.jpg', 'https://picsum.photos/seed/acc-éco-lodge-0-1/800/600', 'https://picsum.photos/seed/acc-éco-lodge-0-2/800/600', 'https://picsum.photos/seed/acc-éco-lodge-0-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 4, description: 'Hébergement Éco-Lodge de qualité en Basse-Casamance, alliant confort moderne et charme local.' },
  { id: 'eco-1', name: 'Éco-Lodge de la Plage', region: 'Moyenne-Casamance', type: 'Éco-Lodge', priceRange: 'A partir de 20 000 FCFA', images: ['https://www.lepapayer.com/pictures/ecolodge-hotel-lepapayer-terrasse-ok.jpg', 'https://picsum.photos/seed/acc-éco-lodge-1-1/800/600', 'https://picsum.photos/seed/acc-éco-lodge-1-2/800/600', 'https://picsum.photos/seed/acc-éco-lodge-1-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 5, description: 'Hébergement Éco-Lodge de qualité en Moyenne-Casamance, alliant confort moderne et charme local.' },
  { id: 'eco-2', name: 'Éco-Lodge du Roi', region: 'Haute-Casamance', type: 'Éco-Lodge', priceRange: 'A partir de 25 000 FCFA', images: ['https://www.cap-skirring.voyage/images/restaurant-ecolodge-sembene-ousmane.jpg?crc=3889602431', 'https://picsum.photos/seed/acc-éco-lodge-2-1/800/600', 'https://picsum.photos/seed/acc-éco-lodge-2-2/800/600', 'https://picsum.photos/seed/acc-éco-lodge-2-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 4, description: 'Hébergement Éco-Lodge de qualité en Haute-Casamance, alliant confort moderne et charme local.' },
  { id: 'eco-3', name: 'Éco-Lodge Soleil', region: 'Basse-Casamance', type: 'Éco-Lodge', priceRange: 'A partir de 30 000 FCFA', images: ['https://www.lepapayer.com/pictures/lepapayer-ecolodge-intrance.jpg', 'https://picsum.photos/seed/acc-éco-lodge-3-1/800/600', 'https://picsum.photos/seed/acc-éco-lodge-3-2/800/600', 'https://picsum.photos/seed/acc-éco-lodge-3-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 5, description: 'Hébergement Éco-Lodge de qualité en Basse-Casamance, alliant confort moderne et charme local.' },
  { id: 'eco-4', name: 'Éco-Lodge Escale', region: 'Moyenne-Casamance', type: 'Éco-Lodge', priceRange: 'A partir de 35 000 FCFA', images: ['https://images.trvl-media.com/lodging/16000000/15730000/15722900/15722887/ece6cd66.jpg?impolicy=resizecrop&rw=575&rh=575&ra=fill', 'https://picsum.photos/seed/acc-éco-lodge-4-1/800/600', 'https://picsum.photos/seed/acc-éco-lodge-4-2/800/600', 'https://picsum.photos/seed/acc-éco-lodge-4-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 4, description: 'Hébergement Éco-Lodge de qualité en Moyenne-Casamance, alliant confort moderne et charme local.' },
  { id: 'eco-5', name: 'Éco-Lodge Teranga', region: 'Haute-Casamance', type: 'Éco-Lodge', priceRange: 'A partir de 40 000 FCFA', images: ['https://dynamic-media-cdn.tripadvisor.com/media/photo-o/28/11/50/30/exterieur-case-tankoano.jpg?w=1200&h=-1&s=1', 'https://picsum.photos/seed/acc-éco-lodge-5-1/800/600', 'https://picsum.photos/seed/acc-éco-lodge-5-2/800/600', 'https://picsum.photos/seed/acc-éco-lodge-5-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 5, description: 'Hébergement Éco-Lodge de qualité en Haute-Casamance, alliant confort moderne et charme local.' },
  { id: 'eco-6', name: 'Éco-Lodge Palmier', region: 'Basse-Casamance', type: 'Éco-Lodge', priceRange: 'A partir de 45 000 FCFA', images: ['https://a0.muscache.com/im/pictures/2b5d0a83-384e-4534-8a49-0398cb9d7b11.jpg', 'https://picsum.photos/seed/acc-éco-lodge-6-1/800/600', 'https://picsum.photos/seed/acc-éco-lodge-6-2/800/600', 'https://picsum.photos/seed/acc-éco-lodge-6-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 4, description: 'Hébergement Éco-Lodge de qualité en Basse-Casamance, alliant confort moderne et charme local.' },
  { id: 'eco-7', name: 'Éco-Lodge Mangrove', region: 'Moyenne-Casamance', type: 'Éco-Lodge', priceRange: 'A partir de 50 000 FCFA', images: ['https://q-xx.bstatic.com/xdata/images/hotel/max500/478078898.jpg?k=d551fbc8fdc1b2711186790b68c9aca4e47ddd56a1dea8f73376ed66f6efb147&o=', 'https://picsum.photos/seed/acc-éco-lodge-7-1/800/600', 'https://picsum.photos/seed/acc-éco-lodge-7-2/800/600', 'https://picsum.photos/seed/acc-éco-lodge-7-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 5, description: 'Hébergement Éco-Lodge de qualité en Moyenne-Casamance, alliant confort moderne et charme local.' },
  { id: 'eco-8', name: 'Éco-Lodge Bolong', region: 'Haute-Casamance', type: 'Éco-Lodge', priceRange: 'A partir de 55 000 FCFA', images: ['https://q-xx.bstatic.com/xdata/images/hotel/max500/480198900.jpg?k=0f660698427de8750994eb435157b19591b89c11bc25f143b0e582da8e9bd0b0&o=', 'https://picsum.photos/seed/acc-éco-lodge-8-1/800/600', 'https://picsum.photos/seed/acc-éco-lodge-8-2/800/600', 'https://picsum.photos/seed/acc-éco-lodge-8-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 4, description: 'Hébergement Éco-Lodge de qualité en Haute-Casamance, alliant confort moderne et charme local.' },
  { id: 'eco-9', name: 'Éco-Lodge Evasion', region: 'Basse-Casamance', type: 'Éco-Lodge', priceRange: 'A partir de 60 000 FCFA', images: ['https://res.cloudinary.com/lastminute/image/upload/w_340,h_260,c_lfill,q_auto,f_auto,g_auto/omsopgwdqjlvaxfndu9e.jpg', 'https://picsum.photos/seed/acc-éco-lodge-9-1/800/600', 'https://picsum.photos/seed/acc-éco-lodge-9-2/800/600', 'https://picsum.photos/seed/acc-éco-lodge-9-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 5, description: 'Hébergement Éco-Lodge de qualité en Basse-Casamance, alliant confort moderne et charme local.' },
  { id: 'eco-10', name: 'Éco-Lodge Sérénité', region: 'Moyenne-Casamance', type: 'Éco-Lodge', priceRange: 'A partir de 65 000 FCFA', images: ['https://q-xx.bstatic.com/xdata/images/hotel/max500/109402854.jpg?k=b2ef635cd90c916fe8b22f0890650393c17016792a83e8d47476df0da9285da2&o=', 'https://picsum.photos/seed/acc-éco-lodge-10-1/800/600', 'https://picsum.photos/seed/acc-éco-lodge-10-2/800/600', 'https://picsum.photos/seed/acc-éco-lodge-10-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 4, description: 'Hébergement Éco-Lodge de qualité en Moyenne-Casamance, alliant confort moderne et charme local.' },
  { id: 'eco-11', name: 'Éco-Lodge Authentique', region: 'Haute-Casamance', type: 'Éco-Lodge', priceRange: 'A partir de 70 000 FCFA', images: ['https://ecolodgedesimal.com/IMG/jpg/chambres-vacances-senegal-213-2.jpg', 'https://picsum.photos/seed/acc-éco-lodge-11-1/800/600', 'https://picsum.photos/seed/acc-éco-lodge-11-2/800/600', 'https://picsum.photos/seed/acc-éco-lodge-11-3/800/600'], features: ['Confort Local', 'Vue Panoramique', 'Restaurant'], rating: 5, description: 'Hébergement Éco-Lodge de qualité en Haute-Casamance, alliant confort moderne et charme local.' },
];

export const DISHES: Dish[] = [
  {
    id: 'dish-1',
    name: 'Caldou',
    description: "Poisson noble poché au citron vert et oseille, plat léger et parfumé des pêcheurs Diola.",
    ingredients: ['Poisson blanc', 'Citron Vert', 'Oseille', 'Oignons', 'Sel', 'Poivre'],
    recipe: ["Mariner le poisson dans le citron vert et les épices 30 minutes", "Faire bouillir l'eau avec les oignons émincés", "Plonger le poisson dans le bouillon frémissant", "Ajouter l'oseille en fin de cuisson", 'Servir avec du riz blanc ou du foutou'],
    price: 'À partir de 1 500 FCFA',
    image: 'https://i.pinimg.com/736x/b3/07/11/b30711683b676af52178840b895f05d6.jpg',
    region: 'Basse-Casamance',
    isVegetarian: false,
  },
  {
    id: 'dish-2',
    name: 'Soupou Kandja',
    description: "Ragoût de gombo sacré à l'huile de palme rouge, plat emblématique de la Moyenne-Casamance.",
    ingredients: ['Gombo frais', 'Huile de Palme', 'Crevettes', 'Poisson fumé', 'Oignons', 'Piment'],
    recipe: ['Laver et hacher finement les gombos', "Cuire les gombos à l'eau bouillante 15 minutes", "Ajouter l'huile de palme rouge et les crevettes", 'Incorporer le poisson fumé émietté', 'Mijoter 20 minutes à feu doux en remuant'],
    price: 'À partir de 3 500 FCFA',
    image: 'https://i.pinimg.com/1200x/30/2a/a1/302aa11d2233dd3ba0a6b5072f6d9cab.jpg',
    region: 'Moyenne-Casamance',
    isVegetarian: false,
  },
  {
    id: 'dish-3',
    name: 'Etodjie',
    description: 'Riz étuvé à la vapeur de bois de palétuvier, recette ancestrale transmise par les femmes Diola.',
    ingredients: ['Riz long grain', 'Poisson séché', 'Bois de palétuvier', 'Sel marin'],
    recipe: ['Laver abondamment le riz à eau froide', 'Allumer un feu avec du bois de palétuvier', 'Cuire le riz à la vapeur dans une marmite en terre cuite', 'Incorporer le poisson séché émietté et mélanger'],
    price: 'À partir de 1 500 FCFA',
    image: 'https://i.pinimg.com/736x/5d/73/2a/5d732af9c73f327bf54ee07cec062b50.jpg',
    region: 'Basse-Casamance',
    isVegetarian: false,
  },
  {
    id: 'dish-4',
    name: 'Yassa Poisson',
    description: "Poisson mariné à l'oignon et citron, grillé au feu de bois — la recette diola par excellence.",
    ingredients: ['Poisson entier', 'Oignons', 'Citron', 'Piment vert', 'Moutarde', "Huile d'arachide"],
    recipe: ["Mariner le poisson dans oignon, citron et moutarde 2 heures", "Faire griller le poisson sur braise de charbon", "Caraméliser les oignons dans l'huile jusqu'à dorure", 'Ajouter la marinade et laisser réduire 15 minutes', 'Incorporer le poisson grillé et mijoter 10 minutes'],
    price: 'À partir de 2 000 FCFA',
    image: 'https://i.pinimg.com/736x/41/59/7b/41597b1a22371d48ce0d8547d45a407e.jpg',
    region: 'Basse-Casamance',
    isVegetarian: false,
  },
  {
    id: 'dish-5',
    name: 'Mafé',
    description: "Sauce arachide onctueuse au bœuf, plat de la Haute-Casamance aux saveurs profondes.",
    ingredients: ["Pâte d'arachide", 'Bœuf', 'Tomates', 'Oignons', 'Piment', 'Épices locales'],
    recipe: ["Faire revenir la viande dans l'huile jusqu'à coloration", "Diluer la pâte d'arachide dans de l'eau tiède", 'Ajouter tomates et oignons à la viande', "Verser la pâte d'arachide et mélanger", 'Mijoter 45 minutes à feu doux en remuant régulièrement'],
    price: 'À partir de 2 000 FCFA',
    image: 'https://i.pinimg.com/736x/93/ac/a7/93aca7100e0743f30beed09c9ef86cea.jpg',
    region: 'Haute-Casamance',
    isVegetarian: false,
  },
  {
    id: 'dish-6',
    name: 'Poisson Braisé',
    description: 'Assortiment de poissons frais grillés aux épices locales sur braise de bois.',
    ingredients: ['Poisson frais', 'Épices locales', 'Ail', 'Gingembre', 'Citron', "Huile de palme"],
    recipe: ['Vider et nettoyer soigneusement les poissons', 'Assaisonner généreusement avec épices et ail pilé', 'Allumer la braise de charbon de bois', 'Braiser les poissons 15 min de chaque côté', "Servir avec sauce tomate et attiéké"],
    price: 'À partir de 5 000 FCFA',
    image: 'https://i.pinimg.com/736x/cd/bd/03/cdbd033a58d587711be697b27e8f7be2.jpg',
    region: 'Basse-Casamance',
    isVegetarian: false,
  },
  {
    id: 'dish-7',
    name: "C'est Bon",
    description: 'Riz et sauce onctueuse aux légumes et poisson, le plat du quotidien qui réunit toute la famille.',
    ingredients: ['Riz', 'Poisson', 'Légumes variés', "Huile d'arachide", 'Tomates', 'Oignons'],
    recipe: ['Cuire le riz selon la méthode traditionnelle', 'Préparer la sauce avec légumes, tomates et poisson', 'Laisser mijoter la sauce 30 minutes', 'Mélanger délicatement riz et sauce', 'Servir chaud dans un plat communautaire'],
    price: 'À partir de 4 000 FCFA',
    image: 'https://i.pinimg.com/736x/c6/d8/f9/c6d8f99823fd9fc4bee490e7c302cfb8.jpg',
    region: 'Basse-Casamance',
    isVegetarian: false,
  },
  {
    id: 'dish-8',
    name: 'Fouti',
    description: "Riz blanc accompagné d'une purée de gombo et d'huile de palme, simplicité et authenticité.",
    ingredients: ['Riz blanc', 'Gombo', 'Huile de palme', 'Sel marin'],
    recipe: ['Cuire le riz à la vapeur selon tradition', "Cuire les gombos entiers à l'eau bouillante", 'Écraser les gombos cuits en purée lisse', "Napper généreusement d'huile de palme rouge", 'Servir riz et purée côte à côte'],
    price: 'À partir de 1 500 FCFA',
    image: 'https://i.pinimg.com/736x/4e/b9/ed/4eb9ed1cdb2022617b7d708dea4a194c.jpg',
    region: 'Moyenne-Casamance',
    isVegetarian: true,
  },
  {
    id: 'dish-9',
    name: 'Domoda',
    description: "Ragoût à la pâte d'arachide avec boulettes de viande ou poisson, richesse du Fouladou.",
    ingredients: ["Pâte d'arachide", 'Viande ou Poisson', 'Tomate', 'Oignons', 'Épices Peules'],
    recipe: ["Diluer la pâte d'arachide dans l'eau tiède", 'Former des boulettes de viande assaisonnées', 'Faire mijoter les protéines dans la sauce', 'Ajouter tomates et épices du Fouladou', "Réduire la sauce jusqu'à consistance onctueuse"],
    price: 'À partir de 2 500 FCFA',
    image: 'https://i.ytimg.com/vi/fbxYgiYMS4Q/sddefault.jpg',
    region: 'Haute-Casamance',
    isVegetarian: false,
  },
];
export const DRINKS: Drink[] = [
  {
    id: 'drink-1',
    name: 'Jus de Ditakh',
    description: 'Nectar vert velouté aux notes de noisette, fruit rare des forêts de Casamance.',
    recipe: ['Peler les fruits de ditakh et récupérer la pulpe', 'Faire tremper la pulpe dans eau tiède 30 minutes', 'Extraire le jus en pressant à travers un tamis fin', 'Filtrer, sucrer légèrement et réfrigérer'],
    price: 'À partir de 1 500 FCFA',
    image: 'https://i.pinimg.com/1200x/a9/6c/08/a96c0887d89f229da7600b7659b244e9.jpg',
    benefits: 'Riche en Vitamine C et antioxydants naturels des forêts tropicales',
  },
  {
    id: 'drink-2',
    name: 'Jus de Bissap',
    description: "Infusion de fleurs d'hibiscus sauvage, la boisson nationale sénégalaise.",
    recipe: ["Faire bouillir 1 litre d'eau", 'Infuser 100g de fleurs de bissap séchées 15 minutes', 'Filtrer et sucrer selon goût', 'Ajouter menthe fraîche et réfrigérer'],
    price: 'À partir de 1 200 FCFA',
    image: 'https://i.pinimg.com/736x/7f/b3/f7/7fb3f72ddddbac0d0c38550823971e2e.jpg',
    benefits: 'Désaltérant et relaxant, régule la tension artérielle naturellement',
  },
  {
    id: 'drink-3',
    name: 'Jus de Bouye',
    description: 'Jus onctueux de fruit du baobab, le superfood ancestral de nos ancêtres.',
    recipe: ['Récupérer la pulpe blanche du fruit du baobab', 'Mixer avec 500ml eau froide et tamiser', 'Ajouter sucre de canne et muscade râpée', 'Servir glacé avec paille'],
    price: 'À partir de 1 500 FCFA',
    image: 'https://i.pinimg.com/736x/25/63/53/256353a10cfbc8894457629b4de16908.jpg',
    benefits: "Apport massif de calcium, 6 fois plus de vitamine C que l'orange",
  },
  {
    id: 'drink-4',
    name: 'Jus de Madd',
    description: 'Nectar acidulé de fruits de liane sauvage, tonique naturel des anciens.',
    recipe: ['Récolter les fruits de madd mûrs', 'Infuser la pulpe dans eau tiède 20 minutes', 'Sucrer légèrement et filtrer finement', 'Servir très frais avec glaçons'],
    price: 'À partir de 2 000 FCFA',
    image: 'https://www.makedasnfood.com/cdn/shop/files/Photoroom_20240530_003348_1.jpg?v=1762021504&width=1100',
    benefits: 'Tonique naturel puissant, régénère et revitalise le système nerveux',
  },
  {
    id: 'drink-5',
    name: 'Jus de Gingembre',
    description: 'Extraction de racine de gingembre frais, le shot énergisant de Casamance.',
    recipe: ['Éplucher et râper 300g de gingembre frais', 'Presser le gingembre râpé pour en extraire le jus', 'Diluer avec eau froide et jus de citron vert', 'Ajouter quelques feuilles de menthe fraîche'],
    price: 'À partir de 1 200 FCFA',
    image: 'https://i.pinimg.com/736x/89/32/2b/89322befe877520769f334de3bab349e.jpg',
    benefits: 'Énergisant puissant, anti-inflammatoire et stimule la circulation sanguine',
  },
  {
    id: 'drink-6',
    name: 'Jus de Tamarin',
    description: 'Jus de tamarin récolté en brousse, aigre-doux rafraîchissant.',
    recipe: ["Faire tremper les gousses de tamarin dans eau tiède 1h", 'Écraser pour dissoudre la pulpe', 'Filtrer finement pour enlever graines et fibres', 'Ajouter du miel de brousse et servir glacé'],
    price: 'À partir de 1 000 FCFA',
    image: 'https://i.pinimg.com/736x/db/a7/98/dba7984f92e659529ca04c9b1cbe4b50.jpg',
    benefits: 'Digestion légère et apaisée, riche en tartrate naturel et fibres',
  },
  {
    id: 'drink-7',
    name: 'Jus de Corossol',
    description: 'Lait de corossol des jardins tropicaux, onctueux et exotique.',
    recipe: ['Récupérer la pulpe blanche du corossol mûr', 'Mixer avec lait de coco et eau froide', 'Ajouter une pointe de vanille de Madagascar', 'Passer au tamis et servir très frais'],
    price: 'À partir de 2 000 FCFA',
    image: 'https://i.pinimg.com/736x/cd/2e/36/cd2e36fba3db9a0673ece6951875dbad.jpg',
    benefits: "Riche en antioxydants, propriétés anti-inflammatoires reconnues",
  },
  {
    id: 'drink-8',
    name: 'Jus de Citronnade',
    description: 'Citrons verts de Casamance et menthe fraîche, fraîcheur absolue garantie.',
    recipe: ['Presser 8 citrons verts bien mûrs', 'Piler une poignée de menthe fraîche au mortier', 'Mélanger jus citron, menthe et eau froide', 'Sucrer avec sirop de canne et servir sur glaçons'],
    price: 'À partir de 1 000 FCFA',
    image: 'https://i.pinimg.com/736x/d3/25/23/d3252349bbac03334549ddf72656b2d2.jpg',
    benefits: "Fraîcheur absolue, vitamine C et minéraux essentiels de l'agrume tropical",
  },
  {
    id: 'drink-9',
    name: 'Jus de Goyave',
    description: 'Nectar de goyaves roses juteuses et parfumées des jardins de Ziguinchor.',
    recipe: ['Laver et couper les goyaves roses en dés', 'Mixer avec eau froide et une pointe de sucre', 'Filtrer finement pour obtenir un jus lisse', 'Servir très frais avec glaçons et une rondelle de citron'],
    price: 'À partir de 2 000 FCFA',
    image: 'https://i.pinimg.com/1200x/0d/62/5c/0d625c42445c868795b9aa94fa935235.jpg',
    benefits: 'Booste le système immunitaire, exceptionnel en vitamine C et lycopène',
  },
];
export const AGENDA_EVENTS: AgendaEvent[] = [
  {
    id: 'e1',
    title: "Festival d'Abéné",
    category: 'Festival Majeur',
    date: 'Fin Déc – Début Jan',
    location: 'Abéné',
    region: 'Basse-Casamance',
    description: "Découverte des cultures casamançaises avec danses diola, mandingue et balante.",
    image: 'https://i.ytimg.com/vi/B8ZP3NsaNhU/maxresdefault.jpg',
    isMajorEvent: true,
    price: 'Gratuit (certains concerts payants)',
    googleMapsUrl: 'https://maps.app.goo.gl/kXvTKV3a79rXfNqD8',
  },
  {
    id: 'e2',
    title: 'Festival du Boukout',
    category: 'Festival Majeur',
    date: 'Mi-décembre',
    location: 'Oussouye ou Bignona',
    region: 'Basse-Casamance',
    description: "Musiques et danses traditionnelles marquant d'importants rituels initiatiques Diola.",
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxunBTIC6wxWGSH6TutpRjqhAQ8-5pSyu5ug&s',
    isMajorEvent: true,
    price: 'Gratuit',
    googleMapsUrl: 'https://maps.app.goo.gl/kXvTKV3a79rXfNqD8',
  },
  {
    id: 'e3',
    title: 'Festival Sacré Diola / Diembering',
    category: 'Festival',
    date: 'Début Avril',
    location: 'Diembering',
    region: 'Basse-Casamance',
    description: "Cérémonies initiatiques, musique et expositions de l'art sacré diola dans un cadre mystique.",
    image: 'https://lens.usercontent.google.com/image?vsrid=CM-F-aWT0P_m1wEQAhgBIiQ2NjVkYzNlOC1iODUzLTQzODktOTJjNS00ZjU3M2YxMzFlZWUyfCICbHUoJUJ0Ci5sZmUtZHVtbXk6MmJiMDYzOTktODQ5YS00OWM1LTg4NGMtNTRmMDk2YWNhYjk5EkIKQC9ibnMvbHUvYm9yZy9sdS9ibnMvbGVucy1mcm9udGVuZC1hcGkvcHJvZC5sZW5zLWZyb250ZW5kLWFwaS8xNTM4teLwv7eTlAM&gsessionid=46r9eGROcXm1fNeYuppcpCkt1__ARIe4zvu-QaUwsAuFhPiKD8YBKQ',
    isMajorEvent: true,
    price: 'Gratuit',
    googleMapsUrl: 'https://maps.app.goo.gl/kXvTKV3a79rXfNqD8',
  },
  {
    id: 'e4',
    title: 'Carnaval et Festival de Kafountine',
    category: 'Festival',
    date: 'Mi-Avril',
    location: 'Kafountine',
    region: 'Basse-Casamance',
    description: "Danses karone, luttes traditionnelles et grand carnaval festif aux couleurs vives.",
    image: 'https://discover-senegal.com/wp-content/uploads/2019/10/Les-Dioulas.jpg',
    isMajorEvent: true,
    price: 'Gratuit',
    googleMapsUrl: 'https://maps.app.goo.gl/kXvTKV3a79rXfNqD8',
  },
  {
    id: 'e5',
    title: 'Festival des Rizières (Kamanu)',
    category: 'Célébration',
    date: 'Avril',
    location: 'Djembéring',
    region: 'Basse-Casamance',
    description: "Célébration agricole et culturelle mettant en valeur la culture du riz, essentielle en Casamance.",
    image: 'https://i.ytimg.com/vi/1KjUJZ2PvRs/maxresdefault.jpg',
    isMajorEvent: false,
    price: 'Gratuit',
    googleMapsUrl: 'https://maps.app.goo.gl/kXvTKV3a79rXfNqD8',
  },
  {
    id: 'e6',
    title: 'Festival de Dombondir',
    category: 'Traditions',
    date: 'Janvier',
    location: 'Près de Kafountine',
    region: 'Basse-Casamance',
    description: "Mise en avant des traditions locales authentiques dans un village préservé de Basse-Casamance.",
    image: 'https://atlanticabene.com/wp-content/uploads/2023/07/17855122_1248224251966110_7277248541277856918_o.jpg',
    isMajorEvent: false,
    price: 'Gratuit',
    googleMapsUrl: 'https://maps.app.goo.gl/kXvTKV3a79rXfNqD8',
  },
  {
    id: 'e7',
    title: 'Festival Koom Koom',
    category: 'Danse & Culture',
    date: 'Variable',
    location: 'Ziguinchor',
    region: 'Basse-Casamance',
    description: "Festival mettant en lumière la danse et l'art musical de la région avec des troupes venues de toute la Casamance.",
    image: 'https://lequotidien.sn/wp-content/uploads/2023/12/FESTIVAL.jpg',
    isMajorEvent: true,
    price: 'Gratuit',
    googleMapsUrl: 'https://maps.app.goo.gl/kXvTKV3a79rXfNqD8',
  },
  {
    id: 'e8',
    title: "Carnaval d'Oussouye",
    category: 'Carnaval',
    date: 'Octobre',
    location: 'Oussouye',
    region: 'Basse-Casamance',
    description: "Grand carnaval animant la ville à l'automne, avec défilés colorés et musiques traditionnelles.",
    image: 'https://www.echoscommunication.org/wp-content/uploads/2023/01/cultures-diolas-2.jpg',
    isMajorEvent: false,
    price: 'Gratuit',
    googleMapsUrl: 'https://maps.app.goo.gl/kXvTKV3a79rXfNqD8',
  },
  {
    id: 'e9',
    title: 'Journées Culturelles de Sédhiou',
    category: 'Exposition & Patrimoine',
    date: 'Décembre',
    location: 'Sédhiou',
    region: 'Moyenne-Casamance',
    description: "Mise en vitrine du patrimoine local mandingue avec spectacles, expositions artisanales et conférences.",
    image: 'https://www.culture.gouv.sn/wp-content/uploads/2020/01/FEMUA-2020D.jpg',
    isMajorEvent: true,
    price: 'Gratuit',
    googleMapsUrl: 'https://maps.app.goo.gl/kXvTKV3a79rXfNqD8',
  },
  {
    id: 'e10',
    title: 'Fête de la Circoncision (Kankourang)',
    category: 'Rituel Mystique',
    date: 'Juin – Octobre',
    location: 'Sédhiou, Kolda, Bignona',
    region: 'Moyenne-Casamance',
    description: "Célébrations dans les villages mandingues avec le personnage mystique Kankourang protégeant les initiés.",
    image: 'https://www.au-senegal.com/local/cache-vignettes/L364xH500/kankourang2-2eb4f.jpg?1727132144',
    isMajorEvent: true,
    price: 'Gratuit',
    googleMapsUrl: 'https://maps.app.goo.gl/kXvTKV3a79rXfNqD8',
  },
  {
    id: 'e11',
    title: 'Gamou Annuel',
    category: 'Religieux & Culturel',
    date: 'Fin Janvier / Mawlid',
    location: 'Kolda',
    region: 'Haute-Casamance',
    description: "Grands rassemblements religieux et culturels réunissant des milliers de fidèles venus de toute la sous-région.",
    image: 'https://www.senegal24news.com/wp-content/uploads/2024/04/Daaka-Medina-Gounass-2-1024x576.jpg',
    isMajorEvent: true,
    price: 'Gratuit',
    googleMapsUrl: 'https://maps.app.goo.gl/kXvTKV3a79rXfNqD8',
  },
  {
    id: 'e12',
    title: 'Rencontres Culturelles et Concerts',
    category: 'Musique & Arts',
    date: 'Printemps',
    location: 'Kolda',
    region: 'Haute-Casamance',
    description: "Initiatives culturelles, concerts et foras organisés par des artistes locaux dont le célèbre Ziko.",
    image: 'https://www.enqueteplus.com/sites/default/files/fouladou.jpg',
    isMajorEvent: false,
    price: 'Variable (certains gratuits, d\'autres payants)',
    googleMapsUrl: 'https://maps.app.goo.gl/kXvTKV3a79rXfNqD8',
  },
];
export const REGIONS_DISCOVERY: RegionDiscovery[] = [
  {
    id: 'basse',
    dbName: 'Basse-Casamance',
    title: 'Basse-Casamance',
    subtitle: 'Terre de l\'eau et des esprits Diola',
    mainDescription: 'La Basse-Casamance est la région la plus connue et la plus visitée. Avec ses plages de sable blanc à Cap Skirring, ses mangroves luxuriantes, ses bolons mystérieux et la ville animée de Ziguinchor, elle offre un cocktail parfait entre nature sauvage et culture Diola vivante. C\'est ici que l\'on trouve les villages traditionnels préservés, les forêts sacrées et les cérémonies initiatiques qui font la renommée mystique de la Casamance.',
    mainImages: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
      'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800',
      'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800',
      'https://images.unsplash.com/photo-1504214208698-ea1916a2195a?w=800',
      'https://images.unsplash.com/photo-1509233725247-49e657c54213?w=800',
    ],
    iconName: 'Waves',
    features: [
      { icon: '🌊', title: 'Plages paradisiaques', description: 'Cap Skirring abrite certaines des plus belles plages d\'Afrique de l\'Ouest avec ses eaux turquoise et son sable blanc immaculé.' },
      { icon: '🌿', title: 'Mangroves mystiques', description: 'Des kilomètres de mangroves abritant une biodiversité exceptionnelle, idéales pour le kayak et l\'observation des oiseaux.' },
      { icon: '🎭', title: 'Culture Diola vivante', description: 'Villages traditionnels préservés, cérémonies initiatiques, danses rituelles et masques sacrés font de cette région un musée vivant.' },
      { icon: '🐦', title: 'Paradis ornithologique', description: 'Plus de 200 espèces d\'oiseaux dont la sterne royale, le martin pêcheur géant et de nombreux migrateurs.' },
      { icon: '🏛️', title: 'Histoire coloniale', description: 'L\'île de Karabane et ses ruines de l\'époque portugaise témoignent des premiers contacts entre l\'Europe et la Casamance.' },
      { icon: '🎋', title: 'Forêts sacrées', description: 'Des bois sacrés préservés jalonnent la campagne, lieux de culte animiste où les esprits des ancêtres sont honorés.' },
    ],
  },
  {
    id: 'moyenne',
    dbName: 'Moyenne-Casamance',
    title: 'Moyenne-Casamance',
    subtitle: 'Confluent des cultures mandingue et peule',
    mainDescription: 'La Moyenne-Casamance est un territoire de transitions et de mélanges. Ici, les cultures Mandingue, Peule et Diola se rencontrent et s\'enrichissent mutuellement. Sédhiou, capitale régionale, est une ville de charme au bord du fleuve, entourée de villages authentiques préservés. Cette région moins touristique offre une immersion plus profonde dans la vie quotidienne des communautés rurales sénégalaises.',
    mainImages: [
      'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800',
      'https://images.unsplash.com/photo-1469521669194-babb45599def?w=800',
      'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800',
      'https://images.unsplash.com/photo-1504214208698-ea1916a2195a?w=800',
    ],
    iconName: 'TreePine',
    features: [
      { icon: '🎵', title: 'Musique de la Kora', description: 'Les griots Mandingues perpétuent l\'art de la kora, instrument à 21 cordes classé au patrimoine immatériel de l\'UNESCO.' },
      { icon: '🐄', title: 'Traditions pastorales Peules', description: 'Les troupeaux de zébus Peuls traversent la région lors des grandes transhumances, spectacle grandiose et authentique.' },
      { icon: '🌳', title: 'Forêts galeries', description: 'Les forêts longeant le fleuve Casamance abritent des espèces végétales rares et une faune abondante.' },
      { icon: '🎨', title: 'Artisanat textile', description: 'Teinture bogolan, tissage sur métier à bras et broderies sont les spécialités artisanales de cette région.' },
      { icon: '🌾', title: 'Agriculture traditionnelle', description: 'Riziculture inondée, cultures de mil et d\'arachide selon des techniques ancestrales transmises de génération en génération.' },
      { icon: '🦋', title: 'Biodiversité exceptionnelle', description: 'Des centaines d\'espèces de papillons tropicaux, hippopotames dans le fleuve et nombreux singes dans les forêts.' },
    ],
  },
  {
    id: 'haute',
    dbName: 'Haute-Casamance',
    title: 'Haute-Casamance',
    subtitle: 'Savane sauvage et parc classé UNESCO',
    mainDescription: 'La Haute-Casamance est la région la plus sauvage et la plus préservée. Dominée par le parc national du Niokolo-Koba, classé au patrimoine mondial de l\'UNESCO, elle abrite une faune exceptionnelle : lions, éléphants, chimpanzés, hippopotames et plus de 350 espèces d\'oiseaux. C\'est la destination des aventuriers et des passionnés de safari qui veulent vivre une expérience africaine authentique loin des circuits touristiques classiques.',
    mainImages: [
      'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800',
      'https://images.unsplash.com/photo-1469521669194-babb45599def?w=800',
      'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
    ],
    iconName: 'Mountain',
    features: [
      { icon: '🦁', title: 'Faune sauvage exceptionnelle', description: 'Lions, éléphants, léopards, hippopotames et chimpanzés cohabitent dans le parc Niokolo-Koba, joyau de la biodiversité africaine.' },
      { icon: '🏛️', title: 'Mégalittes UNESCO', description: 'Les cercles de pierres de la région de Gambie sont classés au patrimoine mondial, témoins d\'une civilisation mystérieuse vieille de 1500 ans.' },
      { icon: '⛰️', title: 'Reliefs et cascades', description: 'Les collines de Kédougou et les cascades de Dindefelo offrent des paysages spectaculaires et des opportunités de trekking uniques.' },
      { icon: '👥', title: 'Peuples Bassari et Bedik', description: 'Ces communautés minoritaires maintiennent des traditions millénaires : danses de masques, initiations et architecture unique en banco.' },
      { icon: '🌌', title: 'Ciel étoilé exceptionnel', description: 'Loin de toute pollution lumineuse, les nuits en savane offrent des spectacles astronomiques époustouflants.' },
      { icon: '🎭', title: 'Festivals culturels', description: 'La Semaine Culturelle Bassari, les marchés de Diaoubé et les célébrations Peules font vibrer la Haute-Casamance toute l\'année.' },
    ],
  },
];

export interface Testimonial {
  id: string;
  author: string;
  content: string;
  rating: number;
  date: string;
  avatar: string;
}

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 't1',
    author: 'Amadou Fall',
    content: 'Un séjour inoubliable à Cap Skirring. Les plages sont paradisiaques, les guides locaux sont exceptionnels et la cuisine est divine. Je reviendrai sans hésiter !',
    rating: 5,
    date: '12 Mars 2024',
    avatar: 'https://i.pravatar.cc/150?u=amadou',
  },
];

export const GALLERY_IMAGES: string[] = [
  // Groupe fixe — items 1–8 (titres dans le catalogue)
  'https://www.au-senegal.com/IMG/jpg/13-23-2.jpg',
  'https://tse3.mm.bing.net/th/id/OIP.Q9OqCgVfgyFBX9madEUiGQHaE8?rs=1&pid=ImgDetMain&o=7&rm=3',
  'https://www.echoscommunication.org/wp-content/uploads/2023/01/0E0O1224_Matar-Ndour.jpg',
  'https://www.wfp.org/sites/default/files/styles/open_graph_image/public/2020-11/migrated-story-hero-images/1*UzVffSICKcFI14ib-rIYkw.jpeg?itok=cPAxHnh1',
  'https://www.au-senegal.com/IMG/jpg/casamance-enchant2-4.jpg',
  'https://i.pinimg.com/1200x/0f/8d/a4/0f8da490bb8d12eb444a773e6e8cafea.jpg',
  'https://www.mycasamance.com/wp-content/uploads/2021/08/5-LA-CASAMANCE-GENEREUSE-ET-AUTHENTIQUE-PAR-NATURE-1.jpg',
  'https://tse1.mm.bing.net/th/id/OIP.8_E-A4R67RO5MALMlOBY8wHaFj?rs=1&pid=ImgDetMain&o=7&rm=3',
  // Groupe dynamique — items 9–34
  'https://tse4.mm.bing.net/th/id/OIP.eqvpHd88J57GQLs_X6vMHAHaE7?rs=1&pid=ImgDetMain&o=7&rm=3',
  'https://casamanceaupresent.com/wp-content/uploads/2017/09/Culture-Diola.jpg',
  'https://sunugox.info/wp-content/uploads/2024/12/IMG_4218.jpeg',
  'https://www.mycasamance.com/wp-content/uploads/2021/08/10-REGION-DE-SEDHIOU-1.jpg',
  'https://pourquoijaimelesenegal.com/images/pjls/sejourner/007-plat-cest-bon-de-la-casamance-article.webp',
  'https://i.ytimg.com/vi/5U7hTImr1PQ/hq720.jpg',
  'https://www.sunugox.info/wp-content/uploads/2025/12/IMG_2840-1024x682.jpeg',
  'https://kumakonda.es/wp-content/uploads/2024/05/Casamance-3.jpg.webp',
  'https://guide-ads.com/wp-content/uploads/2024/07/Linitiation-en-Casamance-8-819x1024.jpg',
  'https://live.staticflickr.com/5463/8982841966_062c56c647_b.jpg',
  'https://img.lemde.fr/2022/08/03/0/0/5905/3937/664/0/75/0/8655e85_1659534928750-sei-lection-mangue-le-monde-1-09.jpg',
  'https://i.pinimg.com/736x/84/fa/5c/84fa5c8d320d77d3e4ffc3696c9f4877.jpg',
  'https://i.pinimg.com/736x/0f/3a/58/0f3a58a936fe15dfacb8e0e7c40fe48f.jpg',
  'https://i.pinimg.com/736x/dc/d0/91/dcd091e6c69bcfcf90c243dc56f987d3.jpg',
  'https://i.pinimg.com/1200x/18/88/fb/1888fb771636014a4534f7d7b57cf13b.jpg',
  'https://images2.bovpg.net/r/media/1/5/6/2/3/562386.jpg',
  'https://discover-senegal.com/wp-content/uploads/2019/05/randonnee_en_casamance_0.jpg',
  'https://discover-senegal.com/wp-content/uploads/2019/05/ornithologie_casamance.jpg',
  'https://www.au-senegal.com/local/cache-vignettes/L820xH431/e23ebdb103acf7fbbd0ae2d97ae461-53d11.jpg',
  'https://www.au-senegal.com/IMG/jpg/campement_aljowe_oussouye_fev_18_17_.jpg',
  'https://www.casamancevtt.com/wp-content/uploads/2023/06/EFOK-LUTTE-BATTEUR.jpg',
  'https://www.destimed.fr/wp-content/uploads/2023/11/P6-1024x819.png',
  'https://th.bing.com/th/id/R.b09223cb6a23441217e84f569f8cf261?rik=qn%2b8SNRTBN5X3Q&pid=ImgRaw&r=0',
  'https://images3.bovpg.net/r/media/1/5/7/2/1/57213.jpg',
  'https://i0.wp.com/www.senegal-shuttle.com/wp-content/uploads/2024/03/Music-and-dance.jpg?resize=522%2C295&ssl=1',
  'https://discover-senegal.com/wp-content/uploads/2019/05/jet-ski.jpg',
];











